package main

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const generated = `// Package x provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package x

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Flight is a flight.
type Flight struct {
	// State is the one-element anyOf.
	State Flight_State ` + "`json:\"state\"`" + `
}

// Flight_State The most up-to-date state.
type Flight_State struct {
	union json.RawMessage
}

// State is a state.
type State struct{ Speed float32 }

// AsState returns the union data inside the Flight_State as a State
func (t Flight_State) AsState() (State, error) {
	var body State
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// MergeState performs a merge with any union data inside the Flight_State, using the provided State
func (t *Flight_State) MergeState(v State) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}
`

// A one-variant union becomes an alias of its variant; its methods, their
// comments, the runtime import, the unused json import and the package
// comment go; the Code generated line stays.
func TestRewriteMakesOneVariantUnionsAliases(t *testing.T) {
	out, n, err := rewrite([]byte(generated))
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	if n != 1 {
		t.Errorf("%d unions rewritten, want 1", n)
	}
	for _, want := range []string{
		"type Flight_State = State",
		"// Flight_State The most up-to-date state.",
		"// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.\npackage x",
		"State Flight_State `json:\"state\"`",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("output lacks %q:\n%s", want, s)
		}
	}
	for _, gone := range []string{"runtime", "encoding/json", "AsState", "MergeState", "union", "provides primitives"} {
		if strings.Contains(s, gone) {
			t.Errorf("output still has %q:\n%s", gone, s)
		}
	}
}

// A union with two variants is a real union: refused, not guessed.
func TestRewriteRefusesARealUnion(t *testing.T) {
	two := strings.Replace(generated, "// MergeState", `// AsOther returns the other variant.
func (t Flight_State) AsOther() (Other, error) {
	var body Other
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// Other is another state.
type Other struct{}

// MergeState`, 1)
	_, _, err := rewrite([]byte(two))
	if err == nil || !strings.Contains(err.Error(), "Flight_State (2 variants") {
		t.Fatalf("a two-variant union: %v", err)
	}
	if _, _, err := rewrite([]byte("package")); err == nil {
		t.Error("unparseable source accepted")
	}
	// One As method whose result is not the type its name says (or not a
	// named type) is not provably one variant: refused.
	for name, as := range map[string]string{
		"result not named": "func (t Flight_State) AsState() ([]State, error) { return nil, nil }",
		"name mismatch":    "func (t Flight_State) AsState() (Other, error) { return Other{}, nil }",
		"no result":        "func (t Flight_State) AsState() {}",
	} {
		src := strings.Replace(generated, `// AsState returns the union data inside the Flight_State as a State
func (t Flight_State) AsState() (State, error) {
	var body State
	err := json.Unmarshal(t.union, &body)
	return body, err
}`, as+"\n\n// Other is other.\ntype Other struct{}", 1)
		if src == generated {
			t.Fatal("the test did not replace AsState")
		}
		if _, _, err := rewrite([]byte(src)); err == nil || !strings.Contains(err.Error(), "?AsState") {
			t.Errorf("%s: %v", name, err)
		}
	}
}

// A file without unions passes through unchanged but for the package
// comment; rewriteFile writes in place.
func TestRewriteFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "types.gen.go")
	src := "// Package y is y.\n//\n// Code generated by tool DO NOT EDIT.\npackage y\n\nimport \"time\"\n\n// T is t.\ntype T struct{ At time.Time }\n"
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := rewriteFile(path); err != nil {
		t.Fatal(err)
	}
	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by tool DO NOT EDIT.\npackage y\n\nimport \"time\"\n\n// T is t.\ntype T struct{ At time.Time }\n"
	if string(out) != want {
		t.Errorf("got\n%s\nwant\n%s", out, want)
	}
	if err := rewriteFile(filepath.Join(t.TempDir(), "missing.go")); err == nil {
		t.Error("a missing file was rewritten")
	}
}

// -source records the generated file's hash in SOURCE, replacing the
// line it wrote before, and the hash ignores CRLF line endings.
func TestRecordHash(t *testing.T) {
	dir := t.TempDir()
	file, source := filepath.Join(dir, "types.gen.go"), filepath.Join(dir, "SOURCE")
	if err := os.WriteFile(file, []byte("package x\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte("# c\nspec_commit = abc\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	for range 2 {
		if err := recordHash(file, source); err != nil {
			t.Fatal(err)
		}
	}
	got, _ := os.ReadFile(source)
	want := "# c\nspec_commit = abc\ngenerated_sha256 = " + GeneratedHash([]byte("package x\n")) + "\n"
	if string(got) != want {
		t.Errorf("SOURCE:\n%s\nwant\n%s", got, want)
	}
	if GeneratedHash([]byte("a\r\nb\r\n")) != GeneratedHash([]byte("a\nb\n")) {
		t.Error("CRLF changes the hash")
	}
	if err := recordHash(filepath.Join(dir, "none.go"), source); err == nil {
		t.Error("a missing file was hashed")
	}
	if err := setKey(filepath.Join(dir, "NONE"), "k", "v"); err == nil {
		t.Error("a missing SOURCE was written")
	}
}

// -check-spec passes only when the fetched file has the recorded hash.
func TestCheckSpecHash(t *testing.T) {
	body := []byte("openapi: 3.0.2\n")
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/missing" {
			http.NotFound(w, r)
			return
		}
		_, _ = w.Write(body)
	}))
	defer srv.Close()
	dir := t.TempDir()
	write := func(url, sum string) string {
		p := filepath.Join(dir, "SOURCE")
		if err := os.WriteFile(p, []byte("spec_url = "+url+"\nspec_sha256 = "+sum+"\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		return p
	}
	right := GeneratedHash(body) // body has no CR: the plain SHA-256
	if err := checkSpecHash(write(srv.URL+"/spec.yaml", right), srv.Client()); err != nil {
		t.Errorf("the pinned file: %v", err)
	}
	if err := checkSpecHash(write(srv.URL+"/spec.yaml", strings.Repeat("0", 64)), srv.Client()); err == nil || !strings.Contains(err.Error(), "changed") {
		t.Errorf("a changed file: %v", err)
	}
	if err := checkSpecHash(write(srv.URL+"/missing", right), srv.Client()); err == nil {
		t.Error("a 404 passed")
	}
	if err := checkSpecHash(write("http://127.0.0.1:1/x", right), srv.Client()); err == nil {
		t.Error("an unreachable host passed")
	}
	if err := checkSpecHash(filepath.Join(dir, "NONE"), srv.Client()); err == nil {
		t.Error("a missing SOURCE passed")
	}
	p := filepath.Join(dir, "SOURCE")
	_ = os.WriteFile(p, []byte("spec_url = x\n"), 0o600)
	if err := checkSpecHash(p, srv.Client()); err == nil {
		t.Error("a SOURCE without spec_sha256 passed")
	}
}
