// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package f3411

import (
	"time"
)

// Defines values for AltitudeReference.
const (
	W84 AltitudeReference = "W84"
)

// Valid indicates whether the value is a known member of the AltitudeReference enum.
func (e AltitudeReference) Valid() bool {
	switch e {
	case W84:
		return true
	default:
		return false
	}
}

// Defines values for AltitudeUnits.
const (
	AltitudeUnitsM AltitudeUnits = "M"
)

// Valid indicates whether the value is a known member of the AltitudeUnits enum.
func (e AltitudeUnits) Valid() bool {
	switch e {
	case AltitudeUnitsM:
		return true
	default:
		return false
	}
}

// Defines values for HorizontalAccuracy.
const (
	HA005NM    HorizontalAccuracy = "HA005NM"
	HA01NM     HorizontalAccuracy = "HA01NM"
	HA03NM     HorizontalAccuracy = "HA03NM"
	HA05NM     HorizontalAccuracy = "HA05NM"
	HA10NM     HorizontalAccuracy = "HA10NM"
	HA10NMPlus HorizontalAccuracy = "HA10NMPlus"
	HA10m      HorizontalAccuracy = "HA10m"
	HA1NM      HorizontalAccuracy = "HA1NM"
	HA1m       HorizontalAccuracy = "HA1m"
	HA2NM      HorizontalAccuracy = "HA2NM"
	HA30m      HorizontalAccuracy = "HA30m"
	HA3m       HorizontalAccuracy = "HA3m"
	HA4NM      HorizontalAccuracy = "HA4NM"
	HAUnknown  HorizontalAccuracy = "HAUnknown"
)

// Valid indicates whether the value is a known member of the HorizontalAccuracy enum.
func (e HorizontalAccuracy) Valid() bool {
	switch e {
	case HA005NM:
		return true
	case HA01NM:
		return true
	case HA03NM:
		return true
	case HA05NM:
		return true
	case HA10NM:
		return true
	case HA10NMPlus:
		return true
	case HA10m:
		return true
	case HA1NM:
		return true
	case HA1m:
		return true
	case HA2NM:
		return true
	case HA30m:
		return true
	case HA3m:
		return true
	case HA4NM:
		return true
	case HAUnknown:
		return true
	default:
		return false
	}
}

// Defines values for OperatorLocationAltitudeType.
const (
	Dynamic OperatorLocationAltitudeType = "Dynamic"
	Fixed   OperatorLocationAltitudeType = "Fixed"
	Takeoff OperatorLocationAltitudeType = "Takeoff"
)

// Valid indicates whether the value is a known member of the OperatorLocationAltitudeType enum.
func (e OperatorLocationAltitudeType) Valid() bool {
	switch e {
	case Dynamic:
		return true
	case Fixed:
		return true
	case Takeoff:
		return true
	default:
		return false
	}
}

// Defines values for RIDHeightReference.
const (
	GroundLevel     RIDHeightReference = "GroundLevel"
	TakeoffLocation RIDHeightReference = "TakeoffLocation"
)

// Valid indicates whether the value is a known member of the RIDHeightReference enum.
func (e RIDHeightReference) Valid() bool {
	switch e {
	case GroundLevel:
		return true
	case TakeoffLocation:
		return true
	default:
		return false
	}
}

// Defines values for RIDOperationalStatus.
const (
	Airborne              RIDOperationalStatus = "Airborne"
	Emergency             RIDOperationalStatus = "Emergency"
	Ground                RIDOperationalStatus = "Ground"
	RemoteIDSystemFailure RIDOperationalStatus = "RemoteIDSystemFailure"
	Undeclared            RIDOperationalStatus = "Undeclared"
)

// Valid indicates whether the value is a known member of the RIDOperationalStatus enum.
func (e RIDOperationalStatus) Valid() bool {
	switch e {
	case Airborne:
		return true
	case Emergency:
		return true
	case Ground:
		return true
	case RemoteIDSystemFailure:
		return true
	case Undeclared:
		return true
	default:
		return false
	}
}

// Defines values for RadiusUnits.
const (
	RadiusUnitsM RadiusUnits = "M"
)

// Valid indicates whether the value is a known member of the RadiusUnits enum.
func (e RadiusUnits) Valid() bool {
	switch e {
	case RadiusUnitsM:
		return true
	default:
		return false
	}
}

// Defines values for SpeedAccuracy.
const (
	SA03mps     SpeedAccuracy = "SA03mps"
	SA10mps     SpeedAccuracy = "SA10mps"
	SA10mpsPlus SpeedAccuracy = "SA10mpsPlus"
	SA1mps      SpeedAccuracy = "SA1mps"
	SA3mps      SpeedAccuracy = "SA3mps"
	SAUnknown   SpeedAccuracy = "SAUnknown"
)

// Valid indicates whether the value is a known member of the SpeedAccuracy enum.
func (e SpeedAccuracy) Valid() bool {
	switch e {
	case SA03mps:
		return true
	case SA10mps:
		return true
	case SA10mpsPlus:
		return true
	case SA1mps:
		return true
	case SA3mps:
		return true
	case SAUnknown:
		return true
	default:
		return false
	}
}

// Defines values for TimeFormat.
const (
	RFC3339 TimeFormat = "RFC3339"
)

// Valid indicates whether the value is a known member of the TimeFormat enum.
func (e TimeFormat) Valid() bool {
	switch e {
	case RFC3339:
		return true
	default:
		return false
	}
}

// Defines values for UAClassificationEUCategory.
const (
	Certified           UAClassificationEUCategory = "Certified"
	EUCategoryUndefined UAClassificationEUCategory = "EUCategoryUndefined"
	Open                UAClassificationEUCategory = "Open"
	Specific            UAClassificationEUCategory = "Specific"
)

// Valid indicates whether the value is a known member of the UAClassificationEUCategory enum.
func (e UAClassificationEUCategory) Valid() bool {
	switch e {
	case Certified:
		return true
	case EUCategoryUndefined:
		return true
	case Open:
		return true
	case Specific:
		return true
	default:
		return false
	}
}

// Defines values for UAClassificationEUClass.
const (
	Class0           UAClassificationEUClass = "Class0"
	Class1           UAClassificationEUClass = "Class1"
	Class2           UAClassificationEUClass = "Class2"
	Class3           UAClassificationEUClass = "Class3"
	Class4           UAClassificationEUClass = "Class4"
	Class5           UAClassificationEUClass = "Class5"
	Class6           UAClassificationEUClass = "Class6"
	EUClassUndefined UAClassificationEUClass = "EUClassUndefined"
)

// Valid indicates whether the value is a known member of the UAClassificationEUClass enum.
func (e UAClassificationEUClass) Valid() bool {
	switch e {
	case Class0:
		return true
	case Class1:
		return true
	case Class2:
		return true
	case Class3:
		return true
	case Class4:
		return true
	case Class5:
		return true
	case Class6:
		return true
	case EUClassUndefined:
		return true
	default:
		return false
	}
}

// Defines values for UAType.
const (
	Aeroplane               UAType = "Aeroplane"
	Airship                 UAType = "Airship"
	CaptiveBalloon          UAType = "CaptiveBalloon"
	FreeBalloon             UAType = "FreeBalloon"
	FreeFallOrParachute     UAType = "FreeFallOrParachute"
	Glider                  UAType = "Glider"
	GroundObstacle          UAType = "GroundObstacle"
	Gyroplane               UAType = "Gyroplane"
	Helicopter              UAType = "Helicopter"
	HybridLift              UAType = "HybridLift"
	Kite                    UAType = "Kite"
	NotDeclared             UAType = "NotDeclared"
	Ornithopter             UAType = "Ornithopter"
	Other                   UAType = "Other"
	Rocket                  UAType = "Rocket"
	TetheredPoweredAircraft UAType = "TetheredPoweredAircraft"
)

// Valid indicates whether the value is a known member of the UAType enum.
func (e UAType) Valid() bool {
	switch e {
	case Aeroplane:
		return true
	case Airship:
		return true
	case CaptiveBalloon:
		return true
	case FreeBalloon:
		return true
	case FreeFallOrParachute:
		return true
	case Glider:
		return true
	case GroundObstacle:
		return true
	case Gyroplane:
		return true
	case Helicopter:
		return true
	case HybridLift:
		return true
	case Kite:
		return true
	case NotDeclared:
		return true
	case Ornithopter:
		return true
	case Other:
		return true
	case Rocket:
		return true
	case TetheredPoweredAircraft:
		return true
	default:
		return false
	}
}

// Defines values for VerticalAccuracy.
const (
	VA10m      VerticalAccuracy = "VA10m"
	VA150m     VerticalAccuracy = "VA150m"
	VA150mPlus VerticalAccuracy = "VA150mPlus"
	VA1m       VerticalAccuracy = "VA1m"
	VA25m      VerticalAccuracy = "VA25m"
	VA3m       VerticalAccuracy = "VA3m"
	VA45m      VerticalAccuracy = "VA45m"
	VAUnknown  VerticalAccuracy = "VAUnknown"
)

// Valid indicates whether the value is a known member of the VerticalAccuracy enum.
func (e VerticalAccuracy) Valid() bool {
	switch e {
	case VA10m:
		return true
	case VA150m:
		return true
	case VA150mPlus:
		return true
	case VA1m:
		return true
	case VA25m:
		return true
	case VA3m:
		return true
	case VA45m:
		return true
	case VAUnknown:
		return true
	default:
		return false
	}
}

// Altitude defines model for Altitude.
type Altitude struct {
	// Reference A code indicating the reference for a vertical distance. See AIXM 5.1 and FIXM 4.2.0. Currently, UTM only allows WGS84 with no immediate plans to allow other options. FIXM and AIXM allow for 'SFC' which is equivalent to AGL.
	Reference AltitudeReference `json:"reference"`

	// Units The reference quantities used to express the value of altitude. See FIXM 4.2. Currently, UTM only allows meters with no immediate plans to allow other options.
	Units AltitudeUnits `json:"units"`

	// Value The numeric value of the altitude. Note that min and max values are added as a sanity check. As use cases evolve and more options are made available in terms of units of measure or reference systems, these bounds may be re-evaluated. Invalid, No Value, or Unknown is –1000 m.
	//
	// Example: 19.5
	Value float64 `json:"value"`
}

// AltitudeReference A code indicating the reference for a vertical distance. See AIXM 5.1 and FIXM 4.2.0. Currently, UTM only allows WGS84 with no immediate plans to allow other options. FIXM and AIXM allow for 'SFC' which is equivalent to AGL.
type AltitudeReference string

// AltitudeUnits The reference quantities used to express the value of altitude. See FIXM 4.2. Currently, UTM only allows meters with no immediate plans to allow other options.
type AltitudeUnits string

// Circle A circular area on the surface of the earth.
type Circle struct {
	// Center Point on the earth's surface.
	Center *LatLngPoint `json:"center,omitempty"`
	Radius *Radius      `json:"radius,omitempty"`
}

// CreateIdentificationServiceAreaParameters Parameters for a request to create an Identification Service Area in the DSS.
type CreateIdentificationServiceAreaParameters struct {
	// Extents The bounding spacetime extents of this Identification Service Area.  End time must be specified.  If start time is not specified, it will be set to the current time.  Start times in the past should be rejected by the DSS, except that it may adjust very recent start times to the current time.
	//
	// These extents should not reveal any sensitive information about the flight or flights within them.  This means, for instance, that extents should not tightly-wrap a flight path, nor should they generally be centered around the takeoff point of a single flight.
	Extents CreateIdentificationServiceAreaParameters_Extents `json:"extents"`

	// UssBaseUrl Base URL for the USS's implementation of the USS API, including the GET flights and GET flights/{id}/details endpoints where flight information can be obtained.
	UssBaseUrl FlightsUSSBaseURL `json:"uss_base_url"`
}

// CreateIdentificationServiceAreaParameters_Extents The bounding spacetime extents of this Identification Service Area.  End time must be specified.  If start time is not specified, it will be set to the current time.  Start times in the past should be rejected by the DSS, except that it may adjust very recent start times to the current time.
//
// These extents should not reveal any sensitive information about the flight or flights within them.  This means, for instance, that extents should not tightly-wrap a flight path, nor should they generally be centered around the takeoff point of a single flight.
type CreateIdentificationServiceAreaParameters_Extents = Volume4D

// CreateSubscriptionParameters Parameters for a request to create a subscription in the DSS.
type CreateSubscriptionParameters struct {
	// Extents The spacetime extents of the volume to subscribe to.
	//
	// This subscription will automatically be deleted after its end time if it has not been refreshed by then.  If end time is not specified, the value will be chosen automatically by the DSS.
	//
	// Note that some Entities triggering notifications may lie entirely outside the requested area.
	Extents CreateSubscriptionParameters_Extents `json:"extents"`

	// UssBaseUrl Base URL for the USS's implementation of the USS API, including the POST identification_service_areas endpoint where notifications for this Subscription will be received.
	UssBaseUrl SubscriptionUSSBaseURL `json:"uss_base_url"`
}

// CreateSubscriptionParameters_Extents The spacetime extents of the volume to subscribe to.
//
// This subscription will automatically be deleted after its end time if it has not been refreshed by then.  If end time is not specified, the value will be chosen automatically by the DSS.
//
// Note that some Entities triggering notifications may lie entirely outside the requested area.
type CreateSubscriptionParameters_Extents = Volume4D

// DeleteIdentificationServiceAreaResponse Response for a request to delete an Identification Service Area.
type DeleteIdentificationServiceAreaResponse struct {
	// ServiceArea Identification Service Area that was just deleted.
	ServiceArea DeleteIdentificationServiceAreaResponse_ServiceArea `json:"service_area"`

	// Subscribers DSS subscribers that this client now has the obligation to notify of the Identification Service Area just deleted.  This client must call POST for each provided URL according to the `/uss/identification_service_areas` path API.
	Subscribers *[]SubscriberToNotify `json:"subscribers,omitempty"`
}

// DeleteIdentificationServiceAreaResponse_ServiceArea Identification Service Area that was just deleted.
type DeleteIdentificationServiceAreaResponse_ServiceArea = IdentificationServiceArea

// DeleteSubscriptionResponse Response for a successful request to delete an Subscription.
type DeleteSubscriptionResponse struct {
	// Subscription The Subscription which was deleted.
	Subscription DeleteSubscriptionResponse_Subscription `json:"subscription"`
}

// DeleteSubscriptionResponse_Subscription The Subscription which was deleted.
type DeleteSubscriptionResponse_Subscription = Subscription

// EntityUUID Universally-unique identifier for an Entity communicated through the DSS.  Formatted as UUIDv4.
type EntityUUID = UUIDv4

// ErrorResponse Data provided when an off-nominal condition was encountered.
type ErrorResponse struct {
	// Message Human-readable message indicating what error occurred and/or why.
	Message *string `json:"message,omitempty"`
}

// FlightsUSSBaseURL Base URL for the USS's implementation of the USS API, including the GET flights and GET flights/{id}/details endpoints where flight information can be obtained.
type FlightsUSSBaseURL = USSBaseURL

// GeoPolygonString Plain-string representation of a geographic polygon consisting of at least three geographic
// points describing a closed polygon on the earth.  Each point consists of latitude,longitude
// in degrees.  Points are also comma-delimited, so this parameter will look like
// `lat1,lng1,lat2,lng2,lat3,lng3,...`  Latitude values must fall in the range [-90, 90] and
// longitude values must fall in the range [-180, 180].
//
// All of the requirements and clarifications for Polygon apply to GeoPolygonString as well.
type GeoPolygonString = string

// GetFlightDetailsResponse Response to remote ID provider query for details about a specific flight.
type GetFlightDetailsResponse struct {
	// Details Details about a flight reported by a remote ID service provider.  At least one of the registration or serial fields must be filled if required by CAA.
	Details RIDFlightDetails `json:"details"`
}

// GetFlightsResponse Response to remote ID provider query for flight information in an area of interest.
type GetFlightsResponse struct {
	// Flights A list of all flights that have been within the requested area within the remote ID retention period.  This includes flights that are not currently within the requested area, but were within the requested area within the remote ID retention period.  Aircraft that are not in flight, and have not been in flight within the retention period, should not be included in this list.
	Flights *[]RIDFlight `json:"flights,omitempty"`

	// NoIsasPresent The requested view is entirely outside any remote ID service provision areas (Identification Service Area volumes) this provider has.  A display provider receiving this response should discontinue polling for this endpoint for the view port requested until otherwise directed by DSS interactions.
	NoIsasPresent *bool `json:"no_isas_present,omitempty"`

	// Timestamp The remote ID service provider's timestamp for when this information was current.
	Timestamp GetFlightsResponse_Timestamp `json:"timestamp"`
}

// GetFlightsResponse_Timestamp The remote ID service provider's timestamp for when this information was current.
type GetFlightsResponse_Timestamp = Time

// GetIdentificationServiceAreaDetailsResponse Response to request for the details of an identification service area with the given ID.
type GetIdentificationServiceAreaDetailsResponse struct {
	// Extents The extents of the Identification Service Area.
	Extents GetIdentificationServiceAreaDetailsResponse_Extents `json:"extents"`
}

// GetIdentificationServiceAreaDetailsResponse_Extents The extents of the Identification Service Area.
type GetIdentificationServiceAreaDetailsResponse_Extents = Volume4D

// GetIdentificationServiceAreaResponse Response to DSS request for the identification service area with the given ID.
type GetIdentificationServiceAreaResponse struct {
	// ServiceArea An Identification Service Area (area in which remote ID services are being provided).  The DSS reports only these declarations and clients must exchange flight information peer-to-peer.
	ServiceArea IdentificationServiceArea `json:"service_area"`
}

// GetSubscriptionResponse Response to DSS request for the subscription with the given id.
type GetSubscriptionResponse struct {
	// Subscription Specification of a geographic area that a client is interested in on an ongoing basis (e.g., "planning area").  Internal to the DSS.
	Subscription Subscription `json:"subscription"`
}

// HorizontalAccuracy This is based on ADS-B NACp (plus the one extra increment).
//
// `HAUnknown`: Unknown horizontal accuracy
//
// `HA10NMPlus`: > 10NM (18.52km)
//
// `HA10NM`: < 10NM (18.52km)
//
// `HA4NM`: < 4NM (7.408km)
//
// `HA2NM`: < 2NM (3.704km)
//
// `HA1NM`: < 1NM (1852m)
//
// `HA05NM`: < 0.5NM (926m)
//
// `HA03NM`: < 0.3NM (555.6m)
//
// `HA01NM`: < 0.1NM (185.2m)
//
// `HA005NM`: < 0.05NM (92.6m)
//
// `HA30m`: < 30m
//
// `HA10m`: < 10m
//
// `HA3m`: < 3m
//
// `HA1m`: < 1m
type HorizontalAccuracy string

// IdentificationServiceArea An Identification Service Area (area in which remote ID services are being provided).  The DSS reports only these declarations and clients must exchange flight information peer-to-peer.
type IdentificationServiceArea struct {
	// Id Unique identifier for this Identification Service Area.
	Id IdentificationServiceArea_Id `json:"id"`

	// Owner Assigned by the DSS based on creating client’s ID (via access token).  Used for restricting mutation and deletion operations to owner.
	//
	// Example: myuss
	Owner string `json:"owner"`

	// TimeEnd End time of service.
	TimeEnd IdentificationServiceArea_TimeEnd `json:"time_end"`

	// TimeStart Beginning time of service.
	TimeStart IdentificationServiceArea_TimeStart `json:"time_start"`

	// UssBaseUrl Base URL for the USS's implementation of the USS API, including the GET flights and GET flights/{id}/details endpoints where flight information can be obtained.
	UssBaseUrl FlightsUSSBaseURL `json:"uss_base_url"`

	// Version A version string used to reference an object at a particular point in time. Any updates to an object must contain the corresponding version to maintain idempotent updates.
	Version Version `json:"version"`
}

// IdentificationServiceArea_Id Unique identifier for this Identification Service Area.
type IdentificationServiceArea_Id = EntityUUID

// IdentificationServiceArea_TimeEnd End time of service.
type IdentificationServiceArea_TimeEnd = Time

// IdentificationServiceArea_TimeStart Beginning time of service.
type IdentificationServiceArea_TimeStart = Time

// LatLngPoint Point on the earth's surface.
type LatLngPoint struct {
	// Lat Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
	//
	// Example: 34.123
	Lat Latitude `json:"lat"`

	// Lng Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
	//
	// Example: -118.456
	Lng Longitude `json:"lng"`
}

// Latitude Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
//
// Example: 34.123
type Latitude = float64

// Longitude Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
//
// Example: -118.456
type Longitude = float64

// OperatingArea Area of operation containing one or more aircraft participating in remote identification.
type OperatingArea struct {
	// AircraftCount Allows for operating a single UA, group, formation, or swarm. Quantity in Group.
	AircraftCount *int32 `json:"aircraft_count,omitempty"`

	// Volumes The area where a group or Intent-Based Network Participant operation is planned or taking place.
	Volumes *[]Volume4D `json:"volumes,omitempty"`
}

// OperatorLocation Location associated with the Remote Pilot
type OperatorLocation struct {
	// Altitude Provides the Operator Altitude based on WGS-84 height above ellipsoid (HAE) (See Geodetic Altitude).  This value is provided in meters and must have a minimum resolution of 1 m.
	Altitude *OperatorLocation_Altitude `json:"altitude,omitempty"`

	// AltitudeType Source of data for the altitude field.
	AltitudeType *OperatorLocationAltitudeType `json:"altitude_type,omitempty"`

	// Position Position of the Remote Pilot.
	Position OperatorLocation_Position `json:"position"`
}

// OperatorLocation_Altitude Provides the Operator Altitude based on WGS-84 height above ellipsoid (HAE) (See Geodetic Altitude).  This value is provided in meters and must have a minimum resolution of 1 m.
type OperatorLocation_Altitude = Altitude

// OperatorLocationAltitudeType Source of data for the altitude field.
type OperatorLocationAltitudeType string

// OperatorLocation_Position Position of the Remote Pilot.
type OperatorLocation_Position = LatLngPoint

// Polygon An enclosed area on the earth. The bounding edges of this polygon are defined to be the shortest paths between connected vertices.  This means, for instance, that the edge between two points both defined at a particular latitude is not generally contained at that latitude. The winding order must be interpreted as the order which produces the smaller area. The path between two vertices is defined to be the shortest possible path between those vertices. Edges may not cross. Vertices may not be duplicated.  In particular, the final polygon vertex must not be identical to the first vertex.
type Polygon struct {
	Vertices []LatLngPoint `json:"vertices"`
}

// PutIdentificationServiceAreaNotificationParameters Parameters of a message informing of new full information for an Identification Service Area.  Pushed (by a client, not the DSS) directly to clients with subscriptions when another client makes a change to airspace within a cell with a subscription.
type PutIdentificationServiceAreaNotificationParameters struct {
	// Extents The new or updated extents of the Identification Service Area.
	//
	// Omitted if Identification Service Area was deleted.
	Extents *PutIdentificationServiceAreaNotificationParameters_Extents `json:"extents,omitempty"`

	// ServiceArea Identification Service Area that the notifying client changed or created.
	//
	// If this field is populated, the Identification Service Area was created or updated.  If this field is not populated, the Identification Service Area was deleted.
	ServiceArea *PutIdentificationServiceAreaNotificationParameters_ServiceArea `json:"service_area,omitempty"`

	// Subscriptions Subscription(s) prompting this notification.
	Subscriptions []SubscriptionState `json:"subscriptions"`
}

// PutIdentificationServiceAreaNotificationParameters_Extents The new or updated extents of the Identification Service Area.
//
// Omitted if Identification Service Area was deleted.
type PutIdentificationServiceAreaNotificationParameters_Extents = Volume4D

// PutIdentificationServiceAreaNotificationParameters_ServiceArea Identification Service Area that the notifying client changed or created.
//
// If this field is populated, the Identification Service Area was created or updated.  If this field is not populated, the Identification Service Area was deleted.
type PutIdentificationServiceAreaNotificationParameters_ServiceArea = IdentificationServiceArea

// PutIdentificationServiceAreaResponse Response to a request to create or update a reference to an Identification Service Area in the DSS.
type PutIdentificationServiceAreaResponse struct {
	// ServiceArea Resulting service area stored in DSS.
	ServiceArea PutIdentificationServiceAreaResponse_ServiceArea `json:"service_area"`

	// Subscribers DSS subscribers that this client now has the obligation to notify of the Identification Service Area changes just made.  This client must call POST for each provided URL according to the `/uss/identification_service_areas/{id}` path API.
	Subscribers *[]SubscriberToNotify `json:"subscribers,omitempty"`
}

// PutIdentificationServiceAreaResponse_ServiceArea Resulting service area stored in DSS.
type PutIdentificationServiceAreaResponse_ServiceArea = IdentificationServiceArea

// PutSubscriptionResponse Response for a request to create or update a subscription.
type PutSubscriptionResponse struct {
	// ServiceAreas Identification Service Areas in or near the subscription area at the time of creation/update, if `identification_service_area_url` callback was specified.
	ServiceAreas *[]IdentificationServiceArea `json:"service_areas,omitempty"`

	// Subscription Result of the operation on the subscription.
	Subscription PutSubscriptionResponse_Subscription `json:"subscription"`
}

// PutSubscriptionResponse_Subscription Result of the operation on the subscription.
type PutSubscriptionResponse_Subscription = Subscription

// RIDAircraftPosition Position of an aircraft as reported for remote ID purposes.
type RIDAircraftPosition struct {
	// AccuracyH Horizontal error that is likely to be present in this reported position.  Required when `extrapolated` field is true and always in the entry for the current state.
	AccuracyH *RIDAircraftPosition_AccuracyH `json:"accuracy_h,omitempty"`

	// AccuracyV Vertical error that is likely to be present in this reported position.  Required when `extrapolated` field is true and always in the entry for the current state.
	AccuracyV *RIDAircraftPosition_AccuracyV `json:"accuracy_v,omitempty"`

	// Alt Geodetic altitude (NOT altitude above launch, altitude above ground, or EGM96): aircraft distance above the WGS84 ellipsoid as measured along a line that passes through the aircraft and is normal to the surface of the WGS84 ellipsoid.  This value is provided in meters and must have a minimum resolution of 1 meter.  Invalid, No Value or Unknown is -1000 m.
	//
	// Example: 1321.2
	Alt *float32 `json:"alt,omitempty"`

	// Extrapolated True if this position was generated primarily by computation rather than primarily from a direct instrument measurement.  Assumed false if not specified.
	Extrapolated *bool `json:"extrapolated,omitempty"`

	// Height A relative altitude for the purposes of remote ID.
	Height *RIDHeight               `json:"height,omitempty"`
	Lat    *RIDAircraftPosition_Lat `json:"lat,omitempty"`
	Lng    *RIDAircraftPosition_Lng `json:"lng,omitempty"`

	// PressureAltitude The uncorrected altitude (based on reference standard 29.92 inHg, 1013.25 mb) provides a reference for algorithms that utilize "altitude deltas" between aircraft.  This value is provided in meters and must have a minimum resolution of 1 meter.  Invalid, No Value or Unknown is -1000 m.
	PressureAltitude *float32 `json:"pressure_altitude,omitempty"`
}

// RIDAircraftPosition_AccuracyH Horizontal error that is likely to be present in this reported position.  Required when `extrapolated` field is true and always in the entry for the current state.
type RIDAircraftPosition_AccuracyH = HorizontalAccuracy

// RIDAircraftPosition_AccuracyV Vertical error that is likely to be present in this reported position.  Required when `extrapolated` field is true and always in the entry for the current state.
type RIDAircraftPosition_AccuracyV = VerticalAccuracy

// RIDAircraftPosition_Lat defines model for RIDAircraftPosition.Lat.
type RIDAircraftPosition_Lat = Latitude

// RIDAircraftPosition_Lng defines model for RIDAircraftPosition.Lng.
type RIDAircraftPosition_Lng = Longitude

// RIDAircraftState State of an aircraft for the purposes of remote ID.
type RIDAircraftState struct {
	// OperationalStatus Operational Status indicates whether the associated UA is on the ground, airborne, or in an
	// emergency situation, or the Remote ID system has failed. The emergency status takes
	// precedence over the other status modes. This status can be used for filtering purposes.
	OperationalStatus *RIDOperationalStatus `json:"operational_status,omitempty"`

	// Position Position of an aircraft as reported for remote ID purposes.
	Position RIDAircraftPosition `json:"position"`

	// Speed Ground speed of flight in meters per second.  Invalid, No Value, or Unknown is 255 m/s, if speed is >254.25 m/s then report 254.25 m/s.
	//
	// Example: 1.9
	Speed *float32 `json:"speed,omitempty"`

	// SpeedAccuracy Provides quality/containment on horizontal ground speed.
	SpeedAccuracy RIDAircraftState_SpeedAccuracy `json:"speed_accuracy"`

	// Timestamp Time at which this state was valid.  This may be the time coming from the source, such as a GPS, or the time when the system computes the values using an algorithm such as an Extended Kalman Filter (EKF).  Timestamp must be expressed with a minimum resolution of 1/10th of a second.
	Timestamp RIDAircraftState_Timestamp `json:"timestamp"`

	// TimestampAccuracy Declaration of timestamp accuracy, which is the largest difference between Timestamp and true time of applicability for any of the following fields: Latitude, Longitude, Geodetic Altitude, Pressure Altitude of Position, Height. to determine time of applicability of the location data provided.  Expressed in seconds, precise to 1/10ths of seconds. The accuracy reflects the 95% uncertainty bound value for the timestamp.
	TimestampAccuracy float32 `json:"timestamp_accuracy"`

	// Track Direction of flight expressed as a "True North-based" ground track angle.  This value is provided in clockwise degrees with a minimum resolution of 1 degree.  If aircraft is not moving horizontally, use the "Unknown" value.  A value of 361 indicates invalid, no value, or unknown.
	Track *float32 `json:"track,omitempty"`

	// VerticalSpeed Speed up (vertically) WGS84-HAE, m/s.  Invalid, No Value, or Unknown is 63 m/s, if speed is >62 m/s then report 62 m/s.
	//
	// Example: 0.2
	VerticalSpeed *float32 `json:"vertical_speed,omitempty"`
}

// RIDAircraftState_SpeedAccuracy Provides quality/containment on horizontal ground speed.
type RIDAircraftState_SpeedAccuracy = SpeedAccuracy

// RIDAircraftState_Timestamp Time at which this state was valid.  This may be the time coming from the source, such as a GPS, or the time when the system computes the values using an algorithm such as an Extended Kalman Filter (EKF).  Timestamp must be expressed with a minimum resolution of 1/10th of a second.
type RIDAircraftState_Timestamp = Time

// RIDAuthData Additional authentication data.
type RIDAuthData struct {
	// Data Authentication data in form specified by `format`.
	Data *string `json:"data,omitempty"`

	// Format Format of additional authentication data.
	//
	// 0: None
	// 1: UAS ID Signature
	// 2: Operator ID Signature
	// 3: Message Set Signature
	// 4: Authentication Provided by Network Remote ID
	// 5: Specific Method
	// 6-9: Reserved for Spec
	// 10-15: Available for Private Use
	Format *int `json:"format,omitempty"`
}

// RIDFlight Description of a remote ID flight.
type RIDFlight struct {
	// AircraftType Generic type of aircraft.
	AircraftType RIDFlight_AircraftType `json:"aircraft_type"`

	// CurrentState The most up-to-date state of the aircraft.  Required when the aircraft is
	// currently in the requested area unless no telemetry is expected during during
	// the flight and `volumes` is specified.
	//
	// If current data is not being received from the UAS by the Service Provider,
	// the lack of change in this field is sufficient to indicate that current
	// data is not being received.
	//
	// If the USS believes a flight is airborne and expects to receive telemetry
	// at some point during the flight but has not yet received telemetry, this
	// field should be populated with the USS's best estimate of the position
	// of the flight with appropriate accuracy indications.
	CurrentState *RIDFlight_CurrentState `json:"current_state,omitempty"`

	// Id ID, unique to a remote ID service provider, which identifies a particular flight for which the remote ID service provider is providing remote ID services.
	//
	// The following characters are not allowed: \0 \t \r \n # % / : ? @ [ \ ]
	//
	// Example: uss1.JA6kHYCcByQ-6AfU
	Id RIDFlightID `json:"id"`

	// OperatingArea The area the aircraft is/are within.  Required, with 1 or more elements, if
	// `current_state` is not specified.  The fields `time_start` and `time_end` are
	// required.
	//
	// If `current_state` is specified, this field should not be specified.
	// If `current_state` was available at any time during the flight, or is
	// expected to be available at any time during the flight, this field should
	// not be specified.
	OperatingArea *RIDFlight_OperatingArea `json:"operating_area,omitempty"`

	// RecentPositions A short collection of recent aircraft movement, specified only when `recent_positions_duration` is greater than zero.  If `volumes` is not specified and `recent_positions_duration` is greater than zero, then this field is required.
	//
	// Recent positions provided in this field must conform to requirements in the standard which generally prohibit including positions outside the requested area except transitionally when the aircraft enters or exits the requested area, and which prohibit including positions that not sufficiently recent.
	//
	// Note that a UI should not draw a connective line between two consecutive position reports that both lie outside the requested area.
	RecentPositions *[]RIDRecentAircraftPosition `json:"recent_positions,omitempty"`

	// Simulated If specified as true, this flight is not a physical aircraft; it is just a simulation to test the system.
	Simulated *bool `json:"simulated,omitempty"`
}

// RIDFlight_AircraftType Generic type of aircraft.
type RIDFlight_AircraftType = UAType

// RIDFlight_CurrentState The most up-to-date state of the aircraft.  Required when the aircraft is
// currently in the requested area unless no telemetry is expected during during
// the flight and `volumes` is specified.
//
// If current data is not being received from the UAS by the Service Provider,
// the lack of change in this field is sufficient to indicate that current
// data is not being received.
//
// If the USS believes a flight is airborne and expects to receive telemetry
// at some point during the flight but has not yet received telemetry, this
// field should be populated with the USS's best estimate of the position
// of the flight with appropriate accuracy indications.
type RIDFlight_CurrentState = RIDAircraftState

// RIDFlight_OperatingArea The area the aircraft is/are within.  Required, with 1 or more elements, if
// `current_state` is not specified.  The fields `time_start` and `time_end` are
// required.
//
// If `current_state` is specified, this field should not be specified.
// If `current_state` was available at any time during the flight, or is
// expected to be available at any time during the flight, this field should
// not be specified.
type RIDFlight_OperatingArea = OperatingArea

// RIDFlightDetails Details about a flight reported by a remote ID service provider.  At least one of the registration or serial fields must be filled if required by CAA.
type RIDFlightDetails struct {
	// AuthData Additional authentication data.
	AuthData *RIDAuthData `json:"auth_data,omitempty"`

	// EuClassification When this field is specified, the Classification Type is "European Union".  If no other classification field is specified, the Classification Type is "Undeclared".
	EuClassification *RIDFlightDetails_EuClassification `json:"eu_classification,omitempty"`

	// Id ID for this flight, matching argument in request.
	//
	// Example: a3423b-213401-0023
	Id string `json:"id"`

	// OperationDescription Free-text field that enables the operator to describe the purpose of a flight, if so desired.
	//
	// Example: SafeFlightDrone company doing survey with DJI Inspire 2. See my privacy policy www.example.com/privacy.
	OperationDescription *string `json:"operation_description,omitempty"`

	// OperatorId This optional field provides a CAA-issued registration/license ID for the remote pilot or operator. Format is <ICAO Nationality MarkA>.<CAA Assigned ID>, ASCII encoded, only uppercase letters (A-Z), dot (.), and digits (0-9) are allowed. Example is valid for the US.
	//
	// Example: N.OP123456
	OperatorId *string `json:"operator_id,omitempty"`

	// OperatorLocation Location associated with the Remote Pilot
	OperatorLocation *OperatorLocation `json:"operator_location,omitempty"`

	// UasId Identification of the UAS performing this flight.  At least one field of this object must be specified.
	UasId *UASID `json:"uas_id,omitempty"`
}

// RIDFlightDetails_EuClassification When this field is specified, the Classification Type is "European Union".  If no other classification field is specified, the Classification Type is "Undeclared".
type RIDFlightDetails_EuClassification = UAClassificationEU

// RIDFlightID ID, unique to a remote ID service provider, which identifies a particular flight for which the remote ID service provider is providing remote ID services.
//
// The following characters are not allowed: \0 \t \r \n # % / : ? @ [ \ ]
//
// Example: uss1.JA6kHYCcByQ-6AfU
type RIDFlightID = string

// RIDHeight A relative altitude for the purposes of remote ID.
type RIDHeight struct {
	// Distance Distance above reference datum.  This value is provided in meters and must have a minimum resolution of 1 meter.  Invalid, No Value or Unknown is -1000 m.
	Distance *float32 `json:"distance,omitempty"`

	// Reference The reference datum above which the height is reported.
	Reference RIDHeightReference `json:"reference"`
}

// RIDHeightReference The reference datum above which the height is reported.
type RIDHeightReference string

// RIDOperationalStatus Operational Status indicates whether the associated UA is on the ground, airborne, or in an
// emergency situation, or the Remote ID system has failed. The emergency status takes
// precedence over the other status modes. This status can be used for filtering purposes.
type RIDOperationalStatus string

// RIDRecentAircraftPosition defines model for RIDRecentAircraftPosition.
type RIDRecentAircraftPosition struct {
	// Position Position of an aircraft as reported for remote ID purposes.
	Position RIDAircraftPosition `json:"position"`

	// Time Time at which this position applied.
	Time RIDRecentAircraftPosition_Time `json:"time"`
}

// RIDRecentAircraftPosition_Time Time at which this position applied.
type RIDRecentAircraftPosition_Time = Time

// Radius defines model for Radius.
type Radius struct {
	// Units FIXM-compatible units.  Only meters ("M") are acceptable for UTM.
	Units RadiusUnits `json:"units"`

	// Value Distance from the centerpoint of a circular area, along the WGS84 ellipsoid.
	//
	// Example: 300.183
	Value float32 `json:"value"`
}

// RadiusUnits FIXM-compatible units.  Only meters ("M") are acceptable for UTM.
type RadiusUnits string

// SearchIdentificationServiceAreasResponse Response to DSS query for Identification Service Areas in an area of interest.
type SearchIdentificationServiceAreasResponse struct {
	// ServiceAreas Identification Service Areas in the area of interest.
	ServiceAreas *[]IdentificationServiceArea `json:"service_areas,omitempty"`
}

// SearchSubscriptionsResponse Response to DSS query for subscriptions in a particular area.
type SearchSubscriptionsResponse struct {
	// Subscriptions Subscriptions that overlap the specified area.
	Subscriptions *[]Subscription `json:"subscriptions,omitempty"`
}

// SpecificSessionID A unique 20 byte ID intended to identify a specific flight (session) while providing a
// greater level of privacy to the operator. The first byte is the registered unique Specific Session ID
// Type maintained by a registrar (see Annex A5), and the remaining 19 bytes is the Session ID per the
// Specific Session ID Type specification.
//
// Initial scheme registry entries include:
//
// 0 – reserved
// 1 – Internet Engineering Task Force (IETF) Drone Remote Identification Protocol (DRIP) entity ID
// 2 – IEEE 1609.2 HashedID8
//
// Expressed as a hexadecimal string of the underlying data bytes.  A recipient should ignore any dashes in this value.  If fewer than 20 bytes are specified, the remaining bytes at the end are assumed to have value 0.
//
// Example: 02-a1b2c3d4e5f60708
type SpecificSessionID = string

// SpeedAccuracy Provides quality/containment on horizontal ground speed.
//
// `SAUnknown`: Unknown speed accuracy
//
// `SA10mpsPlus`: > 10 m/s
//
// `SA10mps`: < 10 m/s
//
// `SA3mps`: < 3 m/s
//
// `SA1mps`: < 1 m/s
//
// `SA03mps`: < 0.3 m/s
type SpeedAccuracy string

// SubscriberToNotify Subscriber to notify of a creation/change/deletion of a change in the airspace.  This is provided by the DSS to a client changing the airspace, and it is the responsibility of the client changing the airspace (they will receive a set of these notification requests) to send a notification to each specified `url`.
type SubscriberToNotify struct {
	// Subscriptions Subscription(s) prompting this notification.
	Subscriptions []SubscriptionState `json:"subscriptions"`

	// Url The endpoint that the client mutating the airspace should provide the update to.  API depends on the DSS action taken that triggered this notification request.
	Url SubscriberToNotify_Url `json:"url"`
}

// SubscriberToNotify_Url The endpoint that the client mutating the airspace should provide the update to.  API depends on the DSS action taken that triggered this notification request.
type SubscriberToNotify_Url = URL

// Subscription Specification of a geographic area that a client is interested in on an ongoing basis (e.g., "planning area").  Internal to the DSS.
type Subscription struct {
	// Id Unique identifier for this subscription.
	Id                Subscription_Id                 `json:"id"`
	NotificationIndex *Subscription_NotificationIndex `json:"notification_index,omitempty"`

	// Owner Assigned by the DSS based on creating client’s ID (via access token).  Used for restricting mutation and deletion operations to owner.
	//
	// Example: myuss
	Owner string `json:"owner"`

	// TimeEnd If set, this subscription will be automatically removed after this time.
	TimeEnd *Subscription_TimeEnd `json:"time_end,omitempty"`

	// TimeStart If set, this Subscription will not generate any notifications before this time.
	TimeStart *Subscription_TimeStart `json:"time_start,omitempty"`

	// UssBaseUrl Base URL for the USS's implementation of the USS API, including the POST identification_service_areas endpoint where notifications for this Subscription will be received.
	UssBaseUrl SubscriptionUSSBaseURL `json:"uss_base_url"`

	// Version A version string used to reference an object at a particular point in time. Any updates to an object must contain the corresponding version to maintain idempotent updates.
	Version Version `json:"version"`
}

// Subscription_Id Unique identifier for this subscription.
type Subscription_Id = SubscriptionUUID

// Subscription_NotificationIndex defines model for Subscription.NotificationIndex.
type Subscription_NotificationIndex = SubscriptionNotificationIndex

// Subscription_TimeEnd If set, this subscription will be automatically removed after this time.
type Subscription_TimeEnd = Time

// Subscription_TimeStart If set, this Subscription will not generate any notifications before this time.
type Subscription_TimeStart = Time

// SubscriptionNotificationIndex Tracks the notifications sent for a subscription so the subscriber can detect missed notifications more easily.
type SubscriptionNotificationIndex = int32

// SubscriptionState State of Subscription which is causing a notification to be sent.
type SubscriptionState struct {
	NotificationIndex *SubscriptionState_NotificationIndex `json:"notification_index,omitempty"`

	// SubscriptionId Universally-unique identifier for a Subscription communicated through the DSS.  Formatted as UUIDv4.
	SubscriptionId SubscriptionUUID `json:"subscription_id"`
}

// SubscriptionState_NotificationIndex defines model for SubscriptionState.NotificationIndex.
type SubscriptionState_NotificationIndex = SubscriptionNotificationIndex

// SubscriptionUSSBaseURL Base URL for the USS's implementation of the USS API, including the POST identification_service_areas endpoint where notifications for this Subscription will be received.
type SubscriptionUSSBaseURL = USSBaseURL

// SubscriptionUUID Universally-unique identifier for a Subscription communicated through the DSS.  Formatted as UUIDv4.
type SubscriptionUUID = UUIDv4

// Time defines model for Time.
type Time struct {
	Format TimeFormat `json:"format"`

	// Value RFC3339-formatted time/date string.  The time zone must be 'Z'.
	//
	// Example: 1985-04-12T23:20:50.52Z
	Value time.Time `json:"value"`
}

// TimeFormat defines model for Time.Format.
type TimeFormat string

// UAClassificationEU defines model for UAClassificationEU.
type UAClassificationEU struct {
	Category *UAClassificationEUCategory `json:"category,omitempty"`
	Class    *UAClassificationEUClass    `json:"class,omitempty"`
}

// UAClassificationEUCategory defines model for UAClassificationEU.Category.
type UAClassificationEUCategory string

// UAClassificationEUClass defines model for UAClassificationEU.Class.
type UAClassificationEUClass string

// UASID Identification of the UAS performing this flight.  At least one field of this object must be specified.
type UASID struct {
	// RegistrationId If a CAA provides a method of registering UAS, this number is provided by the CAA or its authorized representative.  Format is <ICAO Nationality MarkA>.<CAA Assigned ID>, ASCII encoded, only uppercase letters (A-Z), dot (.), and digits (0-9) are allowed. Example is valid for the US.
	//
	// Example: N.123456
	RegistrationId *string `json:"registration_id,omitempty"`

	// SerialNumber This is expressed in the CTA-2063-A Serial Number format.
	//
	// Example: INTCJ123-4567-890
	SerialNumber *string `json:"serial_number,omitempty"`

	// SpecificSessionId A unique 20 byte ID intended to identify a specific flight (session) while providing a
	// greater level of privacy to the operator. The first byte is the registered unique Specific Session ID
	// Type maintained by a registrar (see Annex A5), and the remaining 19 bytes is the Session ID per the
	// Specific Session ID Type specification.
	//
	// Initial scheme registry entries include:
	//
	// 0 – reserved
	// 1 – Internet Engineering Task Force (IETF) Drone Remote Identification Protocol (DRIP) entity ID
	// 2 – IEEE 1609.2 HashedID8
	//
	// Expressed as a hexadecimal string of the underlying data bytes.  A recipient should ignore any dashes in this value.  If fewer than 20 bytes are specified, the remaining bytes at the end are assumed to have value 0.
	//
	// Example: 02-a1b2c3d4e5f60708
	SpecificSessionId *SpecificSessionID `json:"specific_session_id,omitempty"`

	// UtmId A UTM-provided universally unique ID traceable to a non-obfuscated ID that acts as a "session id" to protect exposure of operationally sensitive information.
	//
	// Example: ae1fa066-6d68-4018-8274-af867966978e
	UtmId *string `json:"utm_id,omitempty"`
}

// UAType The UA Type can help infer performance, speed, and duration of flights, for example, a
// "fixed wing" can generally fly in a forward direction only (as compared to a multi-rotor).
// This can also help differentiate aircraft types without sharing operationally sensitive
// information like the make and model of a particular aircraft. Make and model are
// anticipated to become available during the Registration ID lookup process. UAS Type is also
// useful for correlating visual observation with data received. The types were formulated
// based on unique flight characteristics.
//
// `HybridLift` is a fixed wing aircraft that can take off vertically.  `Helicopter` includes multirotor.
type UAType string

// URL Valid http or https URL.
type URL = string

// USSBaseURL The base URL of a USS implementation of part or all of the remote ID USS-USS API. Per the USS-USS API, the full URL
// of a particular resource can be constructed by appending, e.g., `/uss/{resource}/{id}` to this base URL.
// Accordingly, this URL may not have a trailing '/' character.
//
// Example: https://example.com/rid
type USSBaseURL = string

// UUIDv4 UUID v4.
//
// Example: 03e5572a-f733-49af-bc14-8a18bd53ee39
type UUIDv4 = string

// UpdateIdentificationServiceAreaParameters Parameters for a request to update an Identification Service Area in the DSS.
type UpdateIdentificationServiceAreaParameters struct {
	// Extents The bounding spacetime extents of this Identification Service Area.  End time must be specified.  If start time is not specified, it will remain unchanged.  Start times in the past should be rejected by the DSS unless they are unchanged from the Identification Service Area's current start time.
	//
	// These extents should not reveal any sensitive information about the flight or flights within them.  This means, for instance, that extents should not tightly-wrap a flight path, nor should they generally be centered around the takeoff point of a single flight.
	Extents UpdateIdentificationServiceAreaParameters_Extents `json:"extents"`

	// UssBaseUrl Base URL for the USS's implementation of the USS API, including the GET flights and GET flights/{id}/details endpoints where flight information can be obtained.
	UssBaseUrl FlightsUSSBaseURL `json:"uss_base_url"`
}

// UpdateIdentificationServiceAreaParameters_Extents The bounding spacetime extents of this Identification Service Area.  End time must be specified.  If start time is not specified, it will remain unchanged.  Start times in the past should be rejected by the DSS unless they are unchanged from the Identification Service Area's current start time.
//
// These extents should not reveal any sensitive information about the flight or flights within them.  This means, for instance, that extents should not tightly-wrap a flight path, nor should they generally be centered around the takeoff point of a single flight.
type UpdateIdentificationServiceAreaParameters_Extents = Volume4D

// UpdateSubscriptionParameters Parameters for a request to update a subscription in the DSS.
type UpdateSubscriptionParameters struct {
	// Extents The spacetime extents of the volume to subscribe to.
	//
	// This subscription will automatically be deleted after its end time if it has not been refreshed by then.  If end time is not specified, the value will be chosen automatically by the DSS.
	//
	// Note that some Entities triggering notifications may lie entirely outside the requested area.
	Extents UpdateSubscriptionParameters_Extents `json:"extents"`

	// UssBaseUrl Base URL for the USS's implementation of the USS API, including the POST identification_service_areas endpoint where notifications for this Subscription will be received.
	UssBaseUrl SubscriptionUSSBaseURL `json:"uss_base_url"`
}

// UpdateSubscriptionParameters_Extents The spacetime extents of the volume to subscribe to.
//
// This subscription will automatically be deleted after its end time if it has not been refreshed by then.  If end time is not specified, the value will be chosen automatically by the DSS.
//
// Note that some Entities triggering notifications may lie entirely outside the requested area.
type UpdateSubscriptionParameters_Extents = Volume4D

// Version A version string used to reference an object at a particular point in time. Any updates to an object must contain the corresponding version to maintain idempotent updates.
type Version = string

// VerticalAccuracy This is based on ADS-B Geodetic Vertical Accuracy (GVA) (plus the three extra increments)
//
// `VAUnknown`: Unknown vertical accuracy
//
// `VA150mPlus`: > 150m
//
// `VA150m`: < 150m
//
// `VA45m`: < 45m
//
// `VA25m`: < 25m
//
// `VA10m`: < 10m
//
// `VA3m`: < 3m
//
// `VA1m`: < 1m
type VerticalAccuracy string

// Volume3D A three-dimensional geographic volume consisting of a vertically-extruded shape. Exactly one outline must be specified.
type Volume3D struct {
	// AltitudeLower Minimum bounding altitude of this volume. Must be less than altitude_upper, if specified.
	AltitudeLower *Volume3D_AltitudeLower `json:"altitude_lower,omitempty"`

	// AltitudeUpper Maximum bounding altitude of this volume. Must be greater than altitude_lower, if specified.
	AltitudeUpper *Volume3D_AltitudeUpper `json:"altitude_upper,omitempty"`

	// OutlineCircle A circular geographic shape on the surface of the earth.
	OutlineCircle *Volume3D_OutlineCircle `json:"outline_circle,omitempty"`

	// OutlinePolygon A polygonal geographic shape on the surface of the earth.
	OutlinePolygon *Volume3D_OutlinePolygon `json:"outline_polygon,omitempty"`
}

// Volume3D_AltitudeLower Minimum bounding altitude of this volume. Must be less than altitude_upper, if specified.
type Volume3D_AltitudeLower = Altitude

// Volume3D_AltitudeUpper Maximum bounding altitude of this volume. Must be greater than altitude_lower, if specified.
type Volume3D_AltitudeUpper = Altitude

// Volume3D_OutlineCircle A circular geographic shape on the surface of the earth.
type Volume3D_OutlineCircle = Circle

// Volume3D_OutlinePolygon A polygonal geographic shape on the surface of the earth.
type Volume3D_OutlinePolygon = Polygon

// Volume4D Contiguous block of geographic spacetime.
type Volume4D struct {
	// TimeEnd End time of this volume. Must be after time_start.
	TimeEnd *Volume4D_TimeEnd `json:"time_end,omitempty"`

	// TimeStart Beginning time of this volume. Must be before time_end.
	TimeStart *Volume4D_TimeStart `json:"time_start,omitempty"`

	// Volume A three-dimensional geographic volume consisting of a vertically-extruded shape. Exactly one outline must be specified.
	Volume Volume3D `json:"volume"`
}

// Volume4D_TimeEnd End time of this volume. Must be after time_start.
type Volume4D_TimeEnd = Time

// Volume4D_TimeStart Beginning time of this volume. Must be before time_end.
type Volume4D_TimeStart = Time

// SearchIdentificationServiceAreasParams defines parameters for SearchIdentificationServiceAreas.
type SearchIdentificationServiceAreasParams struct {
	// Area The area in which to search for Identification Service Areas.  Some Identification Service Areas near this area but wholly outside it may also be returned.
	Area GeoPolygonString `form:"area" json:"area"`

	// EarliestTime If specified, indicates non-interest in any Identification Service Areas that end before this time.  RFC 3339 format, per OpenAPI specification. The time zone must be 'Z'.
	EarliestTime time.Time `form:"earliest_time" json:"earliest_time"`

	// LatestTime If specified, indicates non-interest in any Identification Service Areas that start after this time.  RFC 3339 format, per OpenAPI specification. The time zone must be 'Z'.
	LatestTime time.Time `form:"latest_time" json:"latest_time"`
}

// SearchSubscriptionsParams defines parameters for SearchSubscriptions.
type SearchSubscriptionsParams struct {
	// Area The area in which to search for Subscriptions.  Some Subscriptions near this area but wholly outside it may also be returned.
	Area GeoPolygonString `form:"area" json:"area"`
}

// SearchFlightsParams defines parameters for SearchFlights.
type SearchFlightsParams struct {
	// View The area of this view: lat1,lng1,lat2,lng2.  Size may not exceed a diagonal length specified in the standard.  The view is the smallest box bounded by the provided corner points.
	View string `form:"view" json:"view"`

	// RecentPositionsDuration If specified as greater than zero, include at least the recent positions within the most recent specified duration in seconds.  Otherwise, do not include recent positions.
	//
	// A display provider's first poll of this endpoint for a particular view will usually request all recent positions while follow-up polls for that same view will usually not need to request all recent positions.
	RecentPositionsDuration *float32 `form:"recent_positions_duration,omitempty" json:"recent_positions_duration,omitempty"`
}

// CreateIdentificationServiceAreaJSONRequestBody defines body for CreateIdentificationServiceArea for application/json ContentType.
type CreateIdentificationServiceAreaJSONRequestBody = CreateIdentificationServiceAreaParameters

// UpdateIdentificationServiceAreaJSONRequestBody defines body for UpdateIdentificationServiceArea for application/json ContentType.
type UpdateIdentificationServiceAreaJSONRequestBody = UpdateIdentificationServiceAreaParameters

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = CreateSubscriptionParameters

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = UpdateSubscriptionParameters

// PostIdentificationServiceAreaJSONRequestBody defines body for PostIdentificationServiceArea for application/json ContentType.
type PostIdentificationServiceAreaJSONRequestBody = PutIdentificationServiceAreaNotificationParameters
