package f3548

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// sourceKey reads `key = value` from SOURCE.
func sourceKey(t *testing.T, key string) string {
	t.Helper()
	raw, err := os.ReadFile("SOURCE")
	if err != nil {
		t.Fatal(err)
	}
	for _, l := range strings.Split(string(raw), "\n") {
		if k, v, ok := strings.Cut(l, "="); ok && strings.TrimSpace(k) == key {
			return strings.TrimSpace(v)
		}
	}
	t.Fatalf("SOURCE has no %s", key)
	return ""
}

// The committed types.gen.go is the file the last go generate wrote: its
// hash is the one oapialias recorded in SOURCE. Offline, so CI checks it
// without running go generate (owner decision on PR #16).
func TestGeneratedTypesUnchanged(t *testing.T) {
	src, err := os.ReadFile("types.gen.go")
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(bytes.ReplaceAll(src, []byte("\r\n"), []byte("\n")))
	if got, want := hex.EncodeToString(sum[:]), sourceKey(t, "generated_sha256"); got != want {
		t.Fatalf("types.gen.go hashes %s, SOURCE records %s: it was edited by hand or regenerated without committing SOURCE", got, want)
	}
	// E-01: one changed byte is caught.
	edited := append(bytes.Clone(src), 'x')
	if e := sha256.Sum256(edited); hex.EncodeToString(e[:]) == sourceKey(t, "generated_sha256") {
		t.Error("an edited file hashes as the recorded one")
	}
	if !bytes.HasPrefix(src, []byte("// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.")) {
		t.Error("types.gen.go does not start with its Code generated line")
	}
	if bytes.Contains(src, []byte("github.com/oapi-codegen/runtime")) {
		t.Error("types.gen.go imports the oapi-codegen runtime")
	}
}

// CI never runs go generate: it needs the network and would make the
// build depend on two upstream hosts (owner decision on PR #16).
func TestCINeverRunsGoGenerate(t *testing.T) {
	ci, err := os.ReadFile(filepath.Join("..", ".github", "workflows", "ci.yml"))
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(ci, []byte("go generate")) {
		t.Error(".github/workflows/ci.yml runs go generate")
	}
}

// go generate fetches the URL SOURCE pins and checks it against
// spec_sha256 first.
func TestGenerateFetchesThePinnedSpec(t *testing.T) {
	gen, err := os.ReadFile("generate.go")
	if err != nil {
		t.Fatal(err)
	}
	url := sourceKey(t, "spec_url")
	if !bytes.Contains(gen, []byte(" "+url+"\n")) {
		t.Errorf("generate.go does not generate from %s", url)
	}
	if !bytes.Contains(gen, []byte("-check-spec SOURCE")) {
		t.Error("generate.go does not check the spec hash")
	}
	if len(sourceKey(t, "spec_sha256")) != 64 {
		t.Error("spec_sha256 is not a SHA-256")
	}
}
