// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package f3548

import (
	"time"
)

// Defines values for AltitudeReference.
const (
	W84 AltitudeReference = "W84"
)

// Valid indicates whether the value is a known member of the AltitudeReference enum.
func (e AltitudeReference) Valid() bool {
	switch e {
	case W84:
		return true
	default:
		return false
	}
}

// Defines values for AltitudeUnits.
const (
	AltitudeUnitsM AltitudeUnits = "M"
)

// Valid indicates whether the value is a known member of the AltitudeUnits enum.
func (e AltitudeUnits) Valid() bool {
	switch e {
	case AltitudeUnitsM:
		return true
	default:
		return false
	}
}

// Defines values for CodeAuthorityRole.
const (
	AUTHORIZATION CodeAuthorityRole = "AUTHORIZATION"
	INFORMATION   CodeAuthorityRole = "INFORMATION"
	NOTIFICATION  CodeAuthorityRole = "NOTIFICATION"
)

// Valid indicates whether the value is a known member of the CodeAuthorityRole enum.
func (e CodeAuthorityRole) Valid() bool {
	switch e {
	case AUTHORIZATION:
		return true
	case INFORMATION:
		return true
	case NOTIFICATION:
		return true
	default:
		return false
	}
}

// Defines values for CodeYesNoType.
const (
	NO  CodeYesNoType = "NO"
	YES CodeYesNoType = "YES"
)

// Valid indicates whether the value is a known member of the CodeYesNoType enum.
func (e CodeYesNoType) Valid() bool {
	switch e {
	case NO:
		return true
	case YES:
		return true
	default:
		return false
	}
}

// Defines values for CodeZoneReasonType.
const (
	AIRTRAFFIC       CodeZoneReasonType = "AIR_TRAFFIC"
	EMERGENCY        CodeZoneReasonType = "EMERGENCY"
	FOREIGNTERRITORY CodeZoneReasonType = "FOREIGN_TERRITORY"
	NATURE           CodeZoneReasonType = "NATURE"
	NOISE            CodeZoneReasonType = "NOISE"
	OTHER            CodeZoneReasonType = "OTHER"
	POPULATION       CodeZoneReasonType = "POPULATION"
	PRIVACY          CodeZoneReasonType = "PRIVACY"
	SENSITIVE        CodeZoneReasonType = "SENSITIVE"
)

// Valid indicates whether the value is a known member of the CodeZoneReasonType enum.
func (e CodeZoneReasonType) Valid() bool {
	switch e {
	case AIRTRAFFIC:
		return true
	case EMERGENCY:
		return true
	case FOREIGNTERRITORY:
		return true
	case NATURE:
		return true
	case NOISE:
		return true
	case OTHER:
		return true
	case POPULATION:
		return true
	case PRIVACY:
		return true
	case SENSITIVE:
		return true
	default:
		return false
	}
}

// Defines values for CodeZoneType.
const (
	COMMON           CodeZoneType = "COMMON"
	CONDITIONAL      CodeZoneType = "CONDITIONAL"
	CUSTOMIZED       CodeZoneType = "CUSTOMIZED"
	NORESTRICTION    CodeZoneType = "NO_RESTRICTION"
	PROHIBITED       CodeZoneType = "PROHIBITED"
	REQAUTHORISATION CodeZoneType = "REQ_AUTHORISATION"
)

// Valid indicates whether the value is a known member of the CodeZoneType enum.
func (e CodeZoneType) Valid() bool {
	switch e {
	case COMMON:
		return true
	case CONDITIONAL:
		return true
	case CUSTOMIZED:
		return true
	case NORESTRICTION:
		return true
	case PROHIBITED:
		return true
	case REQAUTHORISATION:
		return true
	default:
		return false
	}
}

// Defines values for ExchangeRecordRecorderRole.
const (
	Client ExchangeRecordRecorderRole = "Client"
	Server ExchangeRecordRecorderRole = "Server"
)

// Valid indicates whether the value is a known member of the ExchangeRecordRecorderRole enum.
func (e ExchangeRecordRecorderRole) Valid() bool {
	switch e {
	case Client:
		return true
	case Server:
		return true
	default:
		return false
	}
}

// Defines values for OperationalIntentState.
const (
	Accepted      OperationalIntentState = "Accepted"
	Activated     OperationalIntentState = "Activated"
	Contingent    OperationalIntentState = "Contingent"
	Nonconforming OperationalIntentState = "Nonconforming"
)

// Valid indicates whether the value is a known member of the OperationalIntentState enum.
func (e OperationalIntentState) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Activated:
		return true
	case Contingent:
		return true
	case Nonconforming:
		return true
	default:
		return false
	}
}

// Defines values for PositionAccuracyHorizontal.
const (
	HA005NM    PositionAccuracyHorizontal = "HA005NM"
	HA01NM     PositionAccuracyHorizontal = "HA01NM"
	HA03NM     PositionAccuracyHorizontal = "HA03NM"
	HA05NM     PositionAccuracyHorizontal = "HA05NM"
	HA10NM     PositionAccuracyHorizontal = "HA10NM"
	HA10NMPlus PositionAccuracyHorizontal = "HA10NMPlus"
	HA10m      PositionAccuracyHorizontal = "HA10m"
	HA1NM      PositionAccuracyHorizontal = "HA1NM"
	HA1m       PositionAccuracyHorizontal = "HA1m"
	HA2NM      PositionAccuracyHorizontal = "HA2NM"
	HA30m      PositionAccuracyHorizontal = "HA30m"
	HA3m       PositionAccuracyHorizontal = "HA3m"
	HA4NM      PositionAccuracyHorizontal = "HA4NM"
	HAUnknown  PositionAccuracyHorizontal = "HAUnknown"
)

// Valid indicates whether the value is a known member of the PositionAccuracyHorizontal enum.
func (e PositionAccuracyHorizontal) Valid() bool {
	switch e {
	case HA005NM:
		return true
	case HA01NM:
		return true
	case HA03NM:
		return true
	case HA05NM:
		return true
	case HA10NM:
		return true
	case HA10NMPlus:
		return true
	case HA10m:
		return true
	case HA1NM:
		return true
	case HA1m:
		return true
	case HA2NM:
		return true
	case HA30m:
		return true
	case HA3m:
		return true
	case HA4NM:
		return true
	case HAUnknown:
		return true
	default:
		return false
	}
}

// Defines values for PositionAccuracyVertical.
const (
	VA10m      PositionAccuracyVertical = "VA10m"
	VA150m     PositionAccuracyVertical = "VA150m"
	VA150mPlus PositionAccuracyVertical = "VA150mPlus"
	VA1m       PositionAccuracyVertical = "VA1m"
	VA25m      PositionAccuracyVertical = "VA25m"
	VA3m       PositionAccuracyVertical = "VA3m"
	VA45m      PositionAccuracyVertical = "VA45m"
	VAUnknown  PositionAccuracyVertical = "VAUnknown"
)

// Valid indicates whether the value is a known member of the PositionAccuracyVertical enum.
func (e PositionAccuracyVertical) Valid() bool {
	switch e {
	case VA10m:
		return true
	case VA150m:
		return true
	case VA150mPlus:
		return true
	case VA1m:
		return true
	case VA25m:
		return true
	case VA3m:
		return true
	case VA45m:
		return true
	case VAUnknown:
		return true
	default:
		return false
	}
}

// Defines values for RadiusUnits.
const (
	RadiusUnitsM RadiusUnits = "M"
)

// Valid indicates whether the value is a known member of the RadiusUnits enum.
func (e RadiusUnits) Valid() bool {
	switch e {
	case RadiusUnitsM:
		return true
	default:
		return false
	}
}

// Defines values for TimeFormat.
const (
	RFC3339 TimeFormat = "RFC3339"
)

// Valid indicates whether the value is a known member of the TimeFormat enum.
func (e TimeFormat) Valid() bool {
	switch e {
	case RFC3339:
		return true
	default:
		return false
	}
}

// Defines values for UserInputRecordInputTriggeringEvent.
const (
	CMSA0010 UserInputRecordInputTriggeringEvent = "CMSA0010"
	CMSA0025 UserInputRecordInputTriggeringEvent = "CMSA0025"
	CMSA0100 UserInputRecordInputTriggeringEvent = "CMSA0100"
	CMSA0105 UserInputRecordInputTriggeringEvent = "CMSA0105"
	CMSA0110 UserInputRecordInputTriggeringEvent = "CMSA0110"
	CMSA0200 UserInputRecordInputTriggeringEvent = "CMSA0200"
	CMSA0205 UserInputRecordInputTriggeringEvent = "CMSA0205"
	CMSA0210 UserInputRecordInputTriggeringEvent = "CMSA0210"
	CMSA0215 UserInputRecordInputTriggeringEvent = "CMSA0215"
	OPIN0040 UserInputRecordInputTriggeringEvent = "OPIN0040"
)

// Valid indicates whether the value is a known member of the UserInputRecordInputTriggeringEvent enum.
func (e UserInputRecordInputTriggeringEvent) Valid() bool {
	switch e {
	case CMSA0010:
		return true
	case CMSA0025:
		return true
	case CMSA0100:
		return true
	case CMSA0105:
		return true
	case CMSA0110:
		return true
	case CMSA0200:
		return true
	case CMSA0205:
		return true
	case CMSA0210:
		return true
	case CMSA0215:
		return true
	case OPIN0040:
		return true
	default:
		return false
	}
}

// Defines values for UserNotificationRecordNotificationTriggeringEvent.
const (
	ACM0010  UserNotificationRecordNotificationTriggeringEvent = "ACM0010"
	CMSA0115 UserNotificationRecordNotificationTriggeringEvent = "CMSA0115"
	CMSA0300 UserNotificationRecordNotificationTriggeringEvent = "CMSA0300"
	CSTP0005 UserNotificationRecordNotificationTriggeringEvent = "CSTP0005"
	CSTP0010 UserNotificationRecordNotificationTriggeringEvent = "CSTP0010"
	CSTP0020 UserNotificationRecordNotificationTriggeringEvent = "CSTP0020"
	CSTP0025 UserNotificationRecordNotificationTriggeringEvent = "CSTP0025"
	CSTP0030 UserNotificationRecordNotificationTriggeringEvent = "CSTP0030"
	CSTP0035 UserNotificationRecordNotificationTriggeringEvent = "CSTP0035"
	GEN0400  UserNotificationRecordNotificationTriggeringEvent = "GEN0400"
	GEN0405  UserNotificationRecordNotificationTriggeringEvent = "GEN0405"
	SCD0090  UserNotificationRecordNotificationTriggeringEvent = "SCD0090"
	SCD0095  UserNotificationRecordNotificationTriggeringEvent = "SCD0095"
)

// Valid indicates whether the value is a known member of the UserNotificationRecordNotificationTriggeringEvent enum.
func (e UserNotificationRecordNotificationTriggeringEvent) Valid() bool {
	switch e {
	case ACM0010:
		return true
	case CMSA0115:
		return true
	case CMSA0300:
		return true
	case CSTP0005:
		return true
	case CSTP0010:
		return true
	case CSTP0020:
		return true
	case CSTP0025:
		return true
	case CSTP0030:
		return true
	case CSTP0035:
		return true
	case GEN0400:
		return true
	case GEN0405:
		return true
	case SCD0090:
		return true
	case SCD0095:
		return true
	default:
		return false
	}
}

// Defines values for UssAvailabilityState.
const (
	Down    UssAvailabilityState = "Down"
	Normal  UssAvailabilityState = "Normal"
	Unknown UssAvailabilityState = "Unknown"
)

// Valid indicates whether the value is a known member of the UssAvailabilityState enum.
func (e UssAvailabilityState) Valid() bool {
	switch e {
	case Down:
		return true
	case Normal:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for VelocityUnitsSpeed.
const (
	MetersPerSecond VelocityUnitsSpeed = "MetersPerSecond"
)

// Valid indicates whether the value is a known member of the VelocityUnitsSpeed enum.
func (e VelocityUnitsSpeed) Valid() bool {
	switch e {
	case MetersPerSecond:
		return true
	default:
		return false
	}
}

// AirspaceConflictResponse Data provided when an airspace conflict was encountered.
type AirspaceConflictResponse struct {
	// Message Human-readable message indicating what error occurred and/or why.
	Message *string `json:"message,omitempty"`

	// MissingConstraints List of constraint references for which current proof of knowledge was not provided.  If this field is present and contains elements, the calling USS should query the details URLs for these constraints to obtain their details and correct OVNs.  The OVNs can be used to update the key, at which point the USS may retry this call.
	MissingConstraints *[]ConstraintReference `json:"missing_constraints,omitempty"`

	// MissingOperationalIntents List of operational intent references for which current proof of knowledge was not provided.  If this field is present and contains elements, the calling USS should query the details URLs for these operational intents to obtain their details and correct OVNs.  The OVNs can be used to update the key, at which point the USS may retry this call.
	MissingOperationalIntents *[]OperationalIntentReference `json:"missing_operational_intents,omitempty"`
}

// Altitude defines model for Altitude.
type Altitude struct {
	// Reference A code indicating the reference for a vertical distance. See AIXM 5.1 and FIXM 4.2.0. Currently, UTM only allows WGS84 with no immediate plans to allow other options. FIXM and AIXM allow for 'SFC' which is equivalent to AGL.
	Reference AltitudeReference `json:"reference"`

	// Units The reference quantities used to express the value of altitude. See FIXM 4.2. Currently, UTM only allows meters with no immediate plans to allow other options.
	Units AltitudeUnits `json:"units"`

	// Value The numeric value of the altitude. Note that min and max values are added as a sanity check. As use cases evolve and more options are made available in terms of units of measure or reference systems, these bounds may be re-evaluated.
	Value float64 `json:"value"`
}

// AltitudeReference A code indicating the reference for a vertical distance. See AIXM 5.1 and FIXM 4.2.0. Currently, UTM only allows WGS84 with no immediate plans to allow other options. FIXM and AIXM allow for 'SFC' which is equivalent to AGL.
type AltitudeReference string

// AltitudeUnits The reference quantities used to express the value of altitude. See FIXM 4.2. Currently, UTM only allows meters with no immediate plans to allow other options.
type AltitudeUnits string

// Authority A relevant authority that is in charge for authorising, being notified or providing information for UAS operations in the UAS zone.
// Rule: >-
//
//	at least one of the following shall be specified - siteURL, email,
//
// phone.
type Authority struct {
	// ContactName The name or role of a specific person that needs to be contacted within the organisation
	ContactName *Authority_ContactName `json:"contact_name,omitempty"`

	// Email The e-mail address by which the organisation may be contacted.
	// Note: in the data coding format, this might be further constrained in order to ensure a valid e-mail format.
	Email *Authority_Email `json:"email,omitempty"`

	// IntervalBefore The minimal time interval required between notification or authorization request and starting to operate in the zone, in the format PnnDTnnHnnM (ISO 8601).
	IntervalBefore *string `json:"interval_before,omitempty"`

	// Name The official name of a public or private authority
	Name *Authority_Name `json:"name,omitempty"`

	// Phone A phone number at which the organisation may be contacted
	Phone *Authority_Phone `json:"phone,omitempty"`

	// Purpose The role of the Authority in relation with the zone.
	Purpose *Authority_Purpose `json:"purpose,omitempty"`

	// Service The name of a specific department or service within the organisation
	Service *Authority_Service `json:"service,omitempty"`

	// SiteUrl The URL of the public internet site through which the organisation may be contacted
	// Note: in the data coding format, this might be further constrained in order to ensure a valid URL format.
	SiteUrl *Authority_SiteUrl `json:"site_url,omitempty"`
}

// Authority_ContactName The name or role of a specific person that needs to be contacted within the organisation
type Authority_ContactName = TextShortType

// Authority_Email The e-mail address by which the organisation may be contacted.
// Note: in the data coding format, this might be further constrained in order to ensure a valid e-mail format.
type Authority_Email = TextShortType

// Authority_Name The official name of a public or private authority
type Authority_Name = TextShortType

// Authority_Phone A phone number at which the organisation may be contacted
type Authority_Phone = TextShortType

// Authority_Purpose The role of the Authority in relation with the zone.
type Authority_Purpose = CodeAuthorityRole

// Authority_Service The name of a specific department or service within the organisation
type Authority_Service = TextShortType

// Authority_SiteUrl The URL of the public internet site through which the organisation may be contacted
// Note: in the data coding format, this might be further constrained in order to ensure a valid URL format.
type Authority_SiteUrl = TextShortType

// ChangeConstraintReferenceResponse Response to a request to create, update, or delete a ConstraintReference. in the DSS.
type ChangeConstraintReferenceResponse struct {
	// ConstraintReference A ConstraintReference (area in which a constraint is present, along with other high-level information, but no details).  The DSS reports only these references and clients must exchange details and additional information peer-to-peer.
	ConstraintReference ConstraintReference `json:"constraint_reference"`

	// Subscribers DSS subscribers that this client now has the obligation to notify of the constraint changes just made.  This client must call POST for each provided URL according to the USS-USS `/uss/v1/constraints` path API.  The client's own subscriptions will also be included in this list.
	Subscribers []SubscriberToNotify `json:"subscribers"`
}

// ChangeOperationalIntentReferenceResponse Response to a request to create, update, or delete an OperationalIntentReference in the DSS.
type ChangeOperationalIntentReferenceResponse struct {
	// OperationalIntentReference The high-level information of a planned or active operational intent with the URL of a USS to query for details.  Note: 'ovn' is returned ONLY to the USS that created the operational intent but NEVER to other USS instances.
	OperationalIntentReference OperationalIntentReference `json:"operational_intent_reference"`

	// Subscribers DSS subscribers that this client now has the obligation to notify of the operational intent changes just made.  This client must call POST for each provided URL according to the USS-USS `/uss/v1/operational_intents` path API.  The client's own subscriptions will also be included in this list.
	Subscribers []SubscriberToNotify `json:"subscribers"`
}

// Circle A circular area on the surface of the earth.
type Circle struct {
	// Center Point on the earth's surface.
	Center *LatLngPoint `json:"center,omitempty"`
	Radius *Radius      `json:"radius,omitempty"`
}

// CodeAuthorityRole A coded list of values indicating the role that an authority has in relation with the UAS zone.
type CodeAuthorityRole string

// CodeCountryISOType A 3 letter identifier of a country or territory using the ISO 3166-1 alpha-3 standard.
// NOTE: >-
//
//	The ISO 3-letter country codes come with the following advantages:
//	   - allow to distinguish between remote territories and mainland
//	   - are unique, unlike the ICAO Country codes where the same State
//	     could have two or more codes
//	   - are also used in military standards, such as NATO STANAG 1059
//	     INT, which come with well document additions that might be also
//	     useful for UAS areas.
type CodeCountryISOType = string

// CodeRestrictionType An indication if flying in the zone is conditional, forbidden or unrestricted.
type CodeRestrictionType = string

// CodeUSpaceClassType A coded identifier for a category or class of the zone applying a "USpace concept".
// NOTE: >-
//
//	In the current model version, there is no specific list of values.
//
// For example, the “X”, “Y”, “Z” types of zones as per SESAR JU Corus project on USpace concept of operation could be used in a future version. Until a precise list of values is defined, this data type will be considered as string of characters of maximum 100 characters.
type CodeUSpaceClassType = string

// CodeYesNoType A coded value that indicates a choice between a positive (yes) or a negative (no) applicability.
type CodeYesNoType string

// CodeZoneIdentifierType a string of maximum 7 characters that uniquely identifies the area within a geographical scope.
// NOTE (1): This shall not include the country identifier, which is a separate attribute of the UAS Zone.
// NOTE (2): The length of this data type is limited to 7 characters for compatibility with ARINC 424 and AIXM, where an airspace designator may have maximum 10 characters. The 10 characters are the result of concatenating the UAS Zone attributes for country and identifier.
type CodeZoneIdentifierType = string

// CodeZoneReasonType A coded indication of a reason that justifies the existence of an UAS Zone
type CodeZoneReasonType string

// CodeZoneType A coded list of values which allows indicating that the definition of a UAS Zone is specifically customised for a particular UAS or operator.
type CodeZoneType string

// ConditionExpressionType A coded expression that provides information about what is authorised / forbidden in a zone that has conditional access.
// By difference with the “Message” field per zone, this coded expression is made to be interopreted by the UAS while the “Message” is to interpreted by the remote pilot.
// NOTE: the maximum field length is 10 000 characters.
// ---------------------- Condition definition language ---------------- • A list of relevant characteristics (CHARTYPE) has first to be established per state, and their finite list of acceptable values (CHARVAL)
// • Each chartype and charval fields are defined by a limited set of characters
// • A public document shall give the definitions of each, and provide the reference to legal or technical characteristics implied
// • The Geozone editor per state can use these characteristics, with the dedicated condition language defined below, to define exact conditions per zone
// • Each UAS Geofencing function shall be loaded with the corresponding chararacteristic status of the UAS for the intended flight, so as to be able to apply the conditions , either to generate alerts or to limit the flight
// • If the value of a given characteristic of the condition equation is not defined in the UAS, the UAS Geofencing function should inform the pilot in Geoawareness alerting or consider that the zone is forbidden, by default in automatic Geofencing.
// A conditional expression shall be of the following type:
// • The UAS is PERMITTED XOR PROHIBITED (exclusive choice) to fly in this zone at this time IF (Characteristic1) CHARTYPE1 = (Value1) CHARVAL1 AND
// CHARTYPE 2 = CHARVAL 2 AND ... AND End IF
// OR (...)
// ...
// End OR
// • Only the fields in bold need to be edited in the character string, separated by”/”. Others are implicit.
// Examples of CHARTYPE and CHARVALUE:
// • CHARTYPE: operator type; Acceptable CHARVAL values: Military/Police/Firefighting
// • CHARTYPE: Operator ID (registration number); Acceptable CHARVAL values: as per registration format
// • CHARTYPE: Operation type: A1 as per EASA Open Types or S1 (National standard Scenario 1), STS01 (EASA Specific standard scenario) or ...
// • CHARTYPE: UTM operation type: Planned/Unplanned,
// • CHARTYPE: passengers on board: yes /no Note that it is possible in each national catalog of chartype and charval items, to define complex categories of operation/drone /equipment. Example: In nation A, we may have a type “drone level” with values Low, Medium, High. Each level corresponds to a defined set of required UAS performance/operation features/ operator qualification etc. This avoids to code a complex combination in the geozone database. This conditional expression can also be used to code a prohibition of image capture in a zone.
// Example: PERMITTED/IMAGE CAPTURE=NO/NOISE
//
//	CLASS=A/OR/OPERATOR=POLICE
//
// Meaning: >-
//
//	the fight is permitted in this zone at that time if No image is
//
// captured (removed or deactivated) and if noise class = class A (following a known classification) or if the UAS operator is the Police
type ConditionExpressionType = string

// Constraint Full specification of a UTM constraint.
type Constraint struct {
	// Details Details of a UTM constraint. Note that this data is not stored in the DSS; only with the clients.
	Details ConstraintDetails `json:"details"`

	// Reference A ConstraintReference (area in which a constraint is present, along with other high-level information, but no details).  The DSS reports only these references and clients must exchange details and additional information peer-to-peer.
	Reference ConstraintReference `json:"reference"`
}

// ConstraintDetails Details of a UTM constraint. Note that this data is not stored in the DSS; only with the clients.
type ConstraintDetails struct {
	// Geozone If this constraint is an ED-269 compliant geo zone, the details about that geo zone.
	Geozone *ConstraintDetails_Geozone `json:"geozone,omitempty"`

	// Type Type of airspace feature this constraint represents.
	//
	// Example: com.example.non_utm_aircraft_operations
	Type *string `json:"type,omitempty"`

	// Volumes Volumes that wholly contain the constraint while being as small as practical.
	// The end time may not be in the past.
	Volumes []Volume4D `json:"volumes"`
}

// ConstraintDetails_Geozone If this constraint is an ED-269 compliant geo zone, the details about that geo zone.
type ConstraintDetails_Geozone = GeoZone

// ConstraintProviderAssociation Association between a constraint and the constraint provider responsible for that constraint
type ConstraintProviderAssociation struct {
	// ConstraintId ID of constraint to which this association pertains
	ConstraintId ConstraintProviderAssociation_ConstraintId `json:"constraint_id"`

	// ConstraintProviderId Unique identifier of the constraint provider responsible for the constraint
	ConstraintProviderId string `json:"constraint_provider_id"`
}

// ConstraintProviderAssociation_ConstraintId ID of constraint to which this association pertains
type ConstraintProviderAssociation_ConstraintId = EntityID

// ConstraintReference A ConstraintReference (area in which a constraint is present, along with other high-level information, but no details).  The DSS reports only these references and clients must exchange details and additional information peer-to-peer.
type ConstraintReference struct {
	// Id Identifier for an Entity communicated through the DSS.  Formatted as a UUIDv4.
	//
	// Example: 2f8343be-6482-4d1b-a474-16847e01af1e
	Id EntityID `json:"id"`

	// Manager Created by the DSS based on creating client's ID (via access token).  Used internal to the DSS for restricting mutation and deletion operations to manager.  Used by USSs to reject constraint update notifications originating from a USS that does not manage the constraint.
	//
	// Example: uss1
	Manager string `json:"manager"`

	// Ovn Opaque version number of this constraint.  Populated only when the ConstraintReference is managed by the USS retrieving or providing it.  Not populated when the ConstraintReference is not managed by the USS retrieving or providing it (instead, the USS must obtain the OVN from the details retrieved from the managing USS).
	Ovn       *ConstraintReference_Ovn `json:"ovn,omitempty"`
	TimeEnd   Time                     `json:"time_end"`
	TimeStart Time                     `json:"time_start"`

	// UssAvailability A USS is presumed to be in the Unknown state absent indication otherwise by a USS with availability arbitration scope.  Upon determination via availability arbitration, a USS is Down when it does not respond appropriately, and a Down USS may not perform the following operations in the DSS:
	// * Create an operational intent in the Accepted or Activated states
	// * Modify an operational intent whose new or unchanged state is Accepted or Activated
	// * Delete an operational intent
	// A USS in the Unknown state possesses all the capabilities, within the DSS, of a USS in the Normal state.
	UssAvailability UssAvailabilityState `json:"uss_availability"`

	// UssBaseUrl The base URL of a USS implementation that implements the parts of the USS-USS API necessary for providing the details of this constraint.
	UssBaseUrl ConstraintUssBaseURL `json:"uss_base_url"`

	// Version Numeric version of this entity which increments upon each change in the entity, regardless of whether any field of the entity changes.  A USS with the details of this entity when it was at a particular version does not need to retrieve the details again until the version changes.
	//
	// Example: 1
	Version EntityVersion `json:"version"`
}

// ConstraintReference_Ovn Opaque version number of this constraint.  Populated only when the ConstraintReference is managed by the USS retrieving or providing it.  Not populated when the ConstraintReference is not managed by the USS retrieving or providing it (instead, the USS must obtain the OVN from the details retrieved from the managing USS).
type ConstraintReference_Ovn = EntityOVN

// ConstraintUssBaseURL The base URL of a USS implementation that implements the parts of the USS-USS API necessary for providing the details of this constraint.
type ConstraintUssBaseURL = UssBaseURL

// DeleteSubscriptionResponse Response for a successful request to delete a subscription.
type DeleteSubscriptionResponse struct {
	// Subscription Specification of a geographic area that a client is interested in on an ongoing basis (e.g., "planning area").
	Subscription Subscription `json:"subscription"`
}

// EntityID Identifier for an Entity communicated through the DSS.  Formatted as a UUIDv4.
//
// Example: 2f8343be-6482-4d1b-a474-16847e01af1e
type EntityID = UUIDv4Format

// EntityOVN A token associated with a particular UTM Entity+version created by the DSS upon creation or modification of an Entity reference and provided to the client creating or modifying the Entity reference.  The EntityOVN is stored privately by the DSS and then compared against entries in a Key provided to mutate the airspace.  The EntityOVN is also provided by the client whenever that client transmits the full information of the Entity (either via GET, or via a subscription notification).
//
// Example: 9d158f59-80b7-4c11-9c0c-8a2b4d936b2d
type EntityOVN = string

// EntityVersion Numeric version of this entity which increments upon each change in the entity, regardless of whether any field of the entity changes.  A USS with the details of this entity when it was at a particular version does not need to retrieve the details again until the version changes.
//
// Example: 1
type EntityVersion = int32

// ErrorReport A report informing a server of a communication problem.
type ErrorReport struct {
	// Exchange The request (by this USS) and response associated with the error.
	Exchange ErrorReport_Exchange `json:"exchange"`

	// ReportId ID assigned by the server receiving the report.  Not populated when submitting a report.
	ReportId *string `json:"report_id,omitempty"`
}

// ErrorReport_Exchange The request (by this USS) and response associated with the error.
type ErrorReport_Exchange = ExchangeRecord

// ErrorResponse Human-readable string returned when an error occurs as a result of a USS - DSS transaction.
type ErrorResponse struct {
	// Message Human-readable message indicating what error occurred and/or why.
	//
	// Example: The error occurred because [...]
	Message *string `json:"message,omitempty"`
}

// ExchangeRecord Details of a request/response data exchange.
type ExchangeRecord struct {
	// Headers Set of headers associated with request or response. Requires 'Authorization:' field (at a minimum)
	Headers *[]string `json:"headers,omitempty"`

	// Method HTTP verb used by requestor (e.g., "PUT," "GET," etc.)
	Method string `json:"method"`

	// Problem 'Human-readable description of the problem with the exchange, if any.'
	Problem *string `json:"problem,omitempty"`

	// RecorderRole A coded value that indicates the role of the logging USS: 'Client' (initiating a request to a remote USS) or 'Server' (handling a request from a remote USS)
	RecorderRole ExchangeRecordRecorderRole `json:"recorder_role"`

	// RequestBody Base64-encoded body content sent/received as a request.
	RequestBody *string `json:"request_body,omitempty"`

	// RequestTime The time at which the request was sent/received.
	RequestTime ExchangeRecord_RequestTime `json:"request_time"`

	// ResponseBody Base64-encoded body content sent/received in response to request.
	ResponseBody *string `json:"response_body,omitempty"`

	// ResponseCode HTTP response code sent/received in response to request.
	ResponseCode *int32 `json:"response_code,omitempty"`

	// ResponseTime The time at which the response was sent/received.
	ResponseTime *ExchangeRecord_ResponseTime `json:"response_time,omitempty"`

	// Url Full URL of request.
	Url string `json:"url"`
}

// ExchangeRecordRecorderRole A coded value that indicates the role of the logging USS: 'Client' (initiating a request to a remote USS) or 'Server' (handling a request from a remote USS)
type ExchangeRecordRecorderRole string

// ExchangeRecord_RequestTime The time at which the request was sent/received.
type ExchangeRecord_RequestTime = Time

// ExchangeRecord_ResponseTime The time at which the response was sent/received.
type ExchangeRecord_ResponseTime = Time

// GeoZone An airspace of defined dimensions, above the land areas or territorial waters of a State, within which a particular restriction or condition for UAS flights applies.
type GeoZone struct {
	// AdditionalProperties Indicates that exemptions from the national or European regulations are allowed in the UAS Zone, that will be detailed via the "message" property.
	AdditionalProperties *map[string]interface{} `json:"additional_properties,omitempty"`

	// Country The State that has the authority to declare the zone.
	// Note - There will be no Zone belonging to two States. Not necessary to code the information that two zones are "in neighboring States" or "related".
	Country GeoZone_Country `json:"country"`

	// Identifier A string of characters that uniquely identifies the UAS Zone within the State/Territory identified by the country attribute.
	// Note - The UAS Zone is uniquely identified worldwide by the combination of the country and the identifier attributes
	Identifier GeoZone_Identifier `json:"identifier"`

	// Message A message to be displayed to the user of the zone, typically on the RPS for the Remote Pilot, to make him/her aware about specific information associated with the zone (typically when it is not only a restriction to fly in the zone, thus not only an alert or an automatic limitation, for example : “image capture prohibited in this zone”, “frequent strong winds in this zone”, “no landing or take-off in this zone”). This message is also used to indicate exemptions from regulation in a zone (see below). Several information can be grouped in a message, separated by a “/”.
	Message *GeoZone_Message `json:"message,omitempty"`

	// Name A free text name by which the zone may be known by the public or by the UAS community.
	Name *GeoZone_Name `json:"name,omitempty"`

	// OtherReasonInfo A free text description of the reason that led to the establishment of the zone, when not covered by a pre-defined coded value.
	OtherReasonInfo *string `json:"other_reason_info,omitempty"`

	// Reason A coded indication for the reason that led to the establishment of the zone.
	Reason *[]CodeZoneReasonType `json:"reason,omitempty"`

	// Region Where applicable, identifies a region inside a State where the UAS Zone is located.
	// Note 1) identified with a digit between 0-65535 (16 bit), corresponding to a list of regions pre-defined for each State.
	// Note 2) this attribute is intended to facilitate extracting sub-sets of data, for specific regions
	Region *int32 `json:"region,omitempty"`

	// RegulationExemption This is an extension point. It allows adding additional attributes of national interest through this element.
	RegulationExemption *GeoZone_RegulationExemption `json:"regulation_exemption,omitempty"`

	// Restriction An indication if flying in the zone is conditional, forbidden or unrestricted.
	Restriction GeoZone_Restriction `json:"restriction"`

	// RestrictionConditions An indication of the conditions under which the zone can be used
	RestrictionConditions *[]ConditionExpressionType `json:"restriction_conditions,omitempty"`

	// Type An indication whether the Zone is provided with its common definition or with a customised definition, for a particular user.
	Type GeoZone_Type `json:"type"`

	// USpaceClass A code that identifies the category or class of the zone applying a "USpace concept".
	// Note: Two (draft) classifications exist, one from Eurocontrol and one from CORUS. Therefore, two instances of this attribute are expected, one from each sub-list. This might be later replaced with separate attributes and separate lists of values.
	USpaceClass   *GeoZone_USpaceClass `json:"u_space_class,omitempty"`
	ZoneAuthority []Authority          `json:"zone_authority"`
}

// GeoZone_Country The State that has the authority to declare the zone.
// Note - There will be no Zone belonging to two States. Not necessary to code the information that two zones are "in neighboring States" or "related".
type GeoZone_Country = CodeCountryISOType

// GeoZone_Identifier A string of characters that uniquely identifies the UAS Zone within the State/Territory identified by the country attribute.
// Note - The UAS Zone is uniquely identified worldwide by the combination of the country and the identifier attributes
type GeoZone_Identifier = CodeZoneIdentifierType

// GeoZone_Message A message to be displayed to the user of the zone, typically on the RPS for the Remote Pilot, to make him/her aware about specific information associated with the zone (typically when it is not only a restriction to fly in the zone, thus not only an alert or an automatic limitation, for example : “image capture prohibited in this zone”, “frequent strong winds in this zone”, “no landing or take-off in this zone”). This message is also used to indicate exemptions from regulation in a zone (see below). Several information can be grouped in a message, separated by a “/”.
type GeoZone_Message = TextShortType

// GeoZone_Name A free text name by which the zone may be known by the public or by the UAS community.
type GeoZone_Name = TextShortType

// GeoZone_RegulationExemption This is an extension point. It allows adding additional attributes of national interest through this element.
type GeoZone_RegulationExemption = CodeYesNoType

// GeoZone_Restriction An indication if flying in the zone is conditional, forbidden or unrestricted.
type GeoZone_Restriction = CodeRestrictionType

// GeoZone_Type An indication whether the Zone is provided with its common definition or with a customised definition, for a particular user.
type GeoZone_Type = CodeZoneType

// GeoZone_USpaceClass A code that identifies the category or class of the zone applying a "USpace concept".
// Note: Two (draft) classifications exist, one from Eurocontrol and one from CORUS. Therefore, two instances of this attribute are expected, one from each sub-list. This might be later replaced with separate attributes and separate lists of values.
type GeoZone_USpaceClass = CodeUSpaceClassType

// GetConstraintDetailsResponse Response to peer request for the details of operational intent with the given ID.
type GetConstraintDetailsResponse struct {
	// Constraint Full specification of a UTM constraint.
	Constraint Constraint `json:"constraint"`
}

// GetConstraintReferenceResponse Response to DSS request for the ConstraintReference with the given ID.
type GetConstraintReferenceResponse struct {
	// ConstraintReference A ConstraintReference (area in which a constraint is present, along with other high-level information, but no details).  The DSS reports only these references and clients must exchange details and additional information peer-to-peer.
	ConstraintReference ConstraintReference `json:"constraint_reference"`
}

// GetOperationalIntentDetailsResponse Response to peer request for the details of operational intent with the given ID.
type GetOperationalIntentDetailsResponse struct {
	// OperationalIntent Full description of a UTM operational intent.
	OperationalIntent OperationalIntent `json:"operational_intent"`
}

// GetOperationalIntentReferenceResponse Response to DSS request for the OperationalIntentReference with the given ID.
type GetOperationalIntentReferenceResponse struct {
	// OperationalIntentReference The high-level information of a planned or active operational intent with the URL of a USS to query for details.  Note: 'ovn' is returned ONLY to the USS that created the operational intent but NEVER to other USS instances.
	OperationalIntentReference OperationalIntentReference `json:"operational_intent_reference"`
}

// GetOperationalIntentTelemetryResponse Response to a peer request for telemetry of an off-nominal operational intent.
type GetOperationalIntentTelemetryResponse struct {
	// NextTelemetryOpportunity The next telemetry similar to this telemetry is not expected to be available until at or after this time, so the polling USS should generally not poll the endpoint providing this response data again until at or after that time.  If this field is omitted, then there is no current expectation of new telemetry becoming available.
	NextTelemetryOpportunity *GetOperationalIntentTelemetryResponse_NextTelemetryOpportunity `json:"next_telemetry_opportunity,omitempty"`

	// OperationalIntentId ID of the operational intent which the vehicle reporting telemetry is flying.
	OperationalIntentId GetOperationalIntentTelemetryResponse_OperationalIntentId `json:"operational_intent_id"`

	// Telemetry Vehicle position, altitude, and velocity.
	Telemetry *VehicleTelemetry `json:"telemetry,omitempty"`
}

// GetOperationalIntentTelemetryResponse_NextTelemetryOpportunity The next telemetry similar to this telemetry is not expected to be available until at or after this time, so the polling USS should generally not poll the endpoint providing this response data again until at or after that time.  If this field is omitted, then there is no current expectation of new telemetry becoming available.
type GetOperationalIntentTelemetryResponse_NextTelemetryOpportunity = Time

// GetOperationalIntentTelemetryResponse_OperationalIntentId ID of the operational intent which the vehicle reporting telemetry is flying.
type GetOperationalIntentTelemetryResponse_OperationalIntentId = EntityID

// GetSubscriptionResponse Response to DSS request for the subscription with the given id.
type GetSubscriptionResponse struct {
	// Subscription Specification of a geographic area that a client is interested in on an ongoing basis (e.g., "planning area").
	Subscription Subscription `json:"subscription"`
}

// ImplicitSubscriptionParameters Information necessary to create a subscription to serve a single operational intent's notification needs.
type ImplicitSubscriptionParameters struct {
	// NotifyForConstraints True if this operational intent's subscription should trigger notifications when constraints change. Otherwise, changes in constraints should not trigger notifications.  The scope utm.constraint_processing is required to set this flag true, and a USS performing the constraint processing role should set this flag true.
	NotifyForConstraints *bool `json:"notify_for_constraints,omitempty"`

	// UssBaseUrl The base URL of a USS implementation of the parts of the USS-USS API necessary for receiving the notifications that the operational intent must be aware of.  This includes, at least, notifications for relevant changes in operational intents.
	UssBaseUrl ImplicitSubscriptionParameters_UssBaseUrl `json:"uss_base_url"`
}

// ImplicitSubscriptionParameters_UssBaseUrl The base URL of a USS implementation of the parts of the USS-USS API necessary for receiving the notifications that the operational intent must be aware of.  This includes, at least, notifications for relevant changes in operational intents.
type ImplicitSubscriptionParameters_UssBaseUrl = SubscriptionUssBaseURL

// Key Proof that a client has obtained the latest airspace content, used to ensure that write operations to the DSS occur only when the latest content is known (i.e. has been read). The client is required to pass a current Key constructed from information obtained with previous read operations and subsequent requests for full information, and optionally, subscription updates for deconflicted write operations to the DSS.  The contents of this data structure are generated by the client.
type Key = []EntityOVN

// LatLngPoint Point on the earth's surface.
type LatLngPoint struct {
	// Lat Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.
	//
	// Example: 34.123
	Lat Latitude `json:"lat"`

	// Lng Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.
	//
	// Example: -118.456
	Lng Longitude `json:"lng"`
}

// Latitude Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.
//
// Example: 34.123
type Latitude = float64

// Longitude Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.
//
// Example: -118.456
type Longitude = float64

// OperationalIntent Full description of a UTM operational intent.
type OperationalIntent struct {
	// Details Details of a UTM operational intent. Note that this data is not stored in the DSS; only with the clients.
	Details OperationalIntentDetails `json:"details"`

	// Reference The high-level information of a planned or active operational intent with the URL of a USS to query for details.  Note: 'ovn' is returned ONLY to the USS that created the operational intent but NEVER to other USS instances.
	Reference OperationalIntentReference `json:"reference"`
}

// OperationalIntentDetails Details of a UTM operational intent. Note that this data is not stored in the DSS; only with the clients.
type OperationalIntentDetails struct {
	// OffNominalVolumes Volumes that contain the anticipated area of non-conformance while the aircraft is in the Nonconforming or Contingent states.
	// Start and end times, as well as lower and upper altitudes, are required for each volume. The end time may not be in the past.
	// Required with at least one item when the operational intent is Nonconforming or Contingent.
	// May not contain any items when the operational intent is Accepted or Activated.
	OffNominalVolumes *[]Volume4D `json:"off_nominal_volumes,omitempty"`

	// Priority Ordinal priority of the operational intent, as defined by the regulator.  Operational intents with lesser values are lower priority than all operational intents with greater values.  A lower-priority operational intent may not create a conflict with a higher-priority operational intent.  A higher-priority operational intent may create a conflict with a lower-priority operational intent.  The regulator specifies whether an operational intent may create a conflict with other operational intents of the same priority.
	Priority *Priority `json:"priority,omitempty"`

	// Volumes Volumes that wholly contain the operational intent while being as small as practical.
	// Start and end times, as well as lower and upper altitudes, are required for each volume. The end time may not be in the past.
	// Required with at least one item when the operational intent is Accepted, Activated, or Nonconforming.
	// May not contain any items when the operational intent is Contingent.
	Volumes *[]Volume4D `json:"volumes,omitempty"`
}

// OperationalIntentPositions A record of position data gathered through the course of an operational intent
type OperationalIntentPositions struct {
	// OperationalIntentId ID of the operational intent associated with `positions`
	OperationalIntentId OperationalIntentPositions_OperationalIntentId `json:"operational_intent_id"`
	Positions           *[]PositionRecord                              `json:"positions,omitempty"`
}

// OperationalIntentPositions_OperationalIntentId ID of the operational intent associated with `positions`
type OperationalIntentPositions_OperationalIntentId = EntityID

// OperationalIntentReference The high-level information of a planned or active operational intent with the URL of a USS to query for details.  Note: 'ovn' is returned ONLY to the USS that created the operational intent but NEVER to other USS instances.
type OperationalIntentReference struct {
	// Id Identifier for an Entity communicated through the DSS.  Formatted as a UUIDv4.
	//
	// Example: 2f8343be-6482-4d1b-a474-16847e01af1e
	Id EntityID `json:"id"`

	// Manager Created by the DSS based on creating client's ID (via access token).  Used internal to the DSS for restricting mutation and deletion operations to manager.  Used by USSs to reject operational intent update notifications originating from a USS that does not manage the operational intent.
	//
	// Example: uss1
	Manager string `json:"manager"`

	// Ovn Opaque version number of this operational intent.  Populated only when the OperationalIntentReference is managed by the USS retrieving or providing it.  Not populated when the OperationalIntentReference is not managed by the USS retrieving or providing it (instead, the USS must obtain the OVN from the details retrieved from the managing USS).
	Ovn *OperationalIntentReference_Ovn `json:"ovn,omitempty"`

	// State State of an operational intent.
	// 'Accepted': Operational intent is created and shared, but not yet in use; see standard text for more details.
	// The create or update request for this operational intent reference must include a Key containing all OVNs for all relevant Entities.
	// 'Activated': Operational intent is in active use; see standard text for more details.
	// The create or update request for this operational intent reference must include a Key containing all OVNs for all relevant Entities.
	// 'Nonconforming': UA is temporarily outside its volumes, but the situation is expected to be recoverable; see standard text for more details.
	// In this state, the `/uss/v1/operational_intents/{entityid}/telemetry` USS-USS endpoint should respond, if available, to queries from USS peers.  The create or update request for this operational intent may omit a Key in this case because the operational intent is being adjusted as flown and cannot necessarily deconflict.
	// 'Contingent': UA is considered unrecoverably unable to conform with its coordinate operational intent; see standard text for more details.
	// This state must transition to Ended.  In this state, the `/uss/v1/operational_intents/{entityid}/telemetry` USS-USS endpoint should respond, if available, to queries from USS peers.  The create or update request for this operational intent may omit a Key in this case because the operational intent is being adjusted as flown and cannot necessarily deconflict.
	State OperationalIntentState `json:"state"`

	// SubscriptionId The ID of the subscription that is ensuring the operational intent manager receives relevant airspace updates.
	SubscriptionId OperationalIntentReference_SubscriptionId `json:"subscription_id"`

	// TimeEnd End time of operational intent.
	TimeEnd OperationalIntentReference_TimeEnd `json:"time_end"`

	// TimeStart Beginning time of operational intent.
	TimeStart OperationalIntentReference_TimeStart `json:"time_start"`

	// UssAvailability A USS is presumed to be in the Unknown state absent indication otherwise by a USS with availability arbitration scope.  Upon determination via availability arbitration, a USS is Down when it does not respond appropriately, and a Down USS may not perform the following operations in the DSS:
	// * Create an operational intent in the Accepted or Activated states
	// * Modify an operational intent whose new or unchanged state is Accepted or Activated
	// * Delete an operational intent
	// A USS in the Unknown state possesses all the capabilities, within the DSS, of a USS in the Normal state.
	UssAvailability UssAvailabilityState `json:"uss_availability"`

	// UssBaseUrl The base URL of a USS implementation that implements the parts of the USS-USS API necessary for providing the details of this operational intent, and telemetry during non-conformance or contingency, if applicable.
	UssBaseUrl OperationalIntentUssBaseURL `json:"uss_base_url"`

	// Version Numeric version of this entity which increments upon each change in the entity, regardless of whether any field of the entity changes.  A USS with the details of this entity when it was at a particular version does not need to retrieve the details again until the version changes.
	//
	// Example: 1
	Version EntityVersion `json:"version"`
}

// OperationalIntentReference_Ovn Opaque version number of this operational intent.  Populated only when the OperationalIntentReference is managed by the USS retrieving or providing it.  Not populated when the OperationalIntentReference is not managed by the USS retrieving or providing it (instead, the USS must obtain the OVN from the details retrieved from the managing USS).
type OperationalIntentReference_Ovn = EntityOVN

// OperationalIntentReference_SubscriptionId The ID of the subscription that is ensuring the operational intent manager receives relevant airspace updates.
type OperationalIntentReference_SubscriptionId = SubscriptionID

// OperationalIntentReference_TimeEnd End time of operational intent.
type OperationalIntentReference_TimeEnd = Time

// OperationalIntentReference_TimeStart Beginning time of operational intent.
type OperationalIntentReference_TimeStart = Time

// OperationalIntentState State of an operational intent.
// 'Accepted': Operational intent is created and shared, but not yet in use; see standard text for more details.
// The create or update request for this operational intent reference must include a Key containing all OVNs for all relevant Entities.
// 'Activated': Operational intent is in active use; see standard text for more details.
// The create or update request for this operational intent reference must include a Key containing all OVNs for all relevant Entities.
// 'Nonconforming': UA is temporarily outside its volumes, but the situation is expected to be recoverable; see standard text for more details.
// In this state, the `/uss/v1/operational_intents/{entityid}/telemetry` USS-USS endpoint should respond, if available, to queries from USS peers.  The create or update request for this operational intent may omit a Key in this case because the operational intent is being adjusted as flown and cannot necessarily deconflict.
// 'Contingent': UA is considered unrecoverably unable to conform with its coordinate operational intent; see standard text for more details.
// This state must transition to Ended.  In this state, the `/uss/v1/operational_intents/{entityid}/telemetry` USS-USS endpoint should respond, if available, to queries from USS peers.  The create or update request for this operational intent may omit a Key in this case because the operational intent is being adjusted as flown and cannot necessarily deconflict.
type OperationalIntentState string

// OperationalIntentUssBaseURL The base URL of a USS implementation that implements the parts of the USS-USS API necessary for providing the details of this operational intent, and telemetry during non-conformance or contingency, if applicable.
type OperationalIntentUssBaseURL = UssBaseURL

// OperatorAssociation Association between an operational intent and the operator of that operational intent
type OperatorAssociation struct {
	// OperationalIntentId ID of operational intent to which this association pertains
	OperationalIntentId OperatorAssociation_OperationalIntentId `json:"operational_intent_id"`

	// OperatorId Unique identifier of the operator responsible for the operational intent
	OperatorId string `json:"operator_id"`
}

// OperatorAssociation_OperationalIntentId ID of operational intent to which this association pertains
type OperatorAssociation_OperationalIntentId = EntityID

// PlanningRecord A record of a single attempt to (successfully or unsuccessfully) create or modify an operational intent.
type PlanningRecord struct {
	// MissingConstraints List of missing constraints (for planning attempts that were denied by the DSS with code 409)
	MissingConstraints *[]EntityID `json:"missing_constraints,omitempty"`

	// MissingOperationalIntents List of missing operational intents (for planning attempts that were denied by the DSS with code 409)
	MissingOperationalIntents *[]EntityID `json:"missing_operational_intents,omitempty"`

	// OperationalIntentId ID of the operational intent being planned
	OperationalIntentId *PlanningRecord_OperationalIntentId `json:"operational_intent_id,omitempty"`

	// Ovns OVNs the planning USS was aware of when it was planning the operational intent
	Ovns []EntityOVN `json:"ovns"`

	// Problem A free text description of the problem(s) encountered during this planning attempt.
	Problem *string `json:"problem,omitempty"`

	// Time Time that this planning event occurred
	Time PlanningRecord_Time `json:"time"`
}

// PlanningRecord_OperationalIntentId ID of the operational intent being planned
type PlanningRecord_OperationalIntentId = EntityID

// PlanningRecord_Time Time that this planning event occurred
type PlanningRecord_Time = Time

// Polygon An enclosed area on the earth. The bounding edges of this polygon are defined to be the shortest paths between connected vertices.  This means, for instance, that the edge between two points both defined at a particular latitude is not generally contained at that latitude. The winding order must be interpreted as the order which produces the smaller area. The path between two vertices is defined to be the shortest possible path between those vertices. Edges may not cross. Vertices may not be duplicated.  In particular, the final polygon vertex must not be identical to the first vertex.
type Polygon struct {
	Vertices []LatLngPoint `json:"vertices"`
}

// Position Location of the vehicle (UAS) as reported for UTM. Note: 'accuracy' values are required when extrapolated field is true.
type Position struct {
	// AccuracyH Horizontal error that is likely to be present in this reported position. This is the NACp enumeration from ADS-B, plus 1m for a more complete range for UAS.
	AccuracyH *PositionAccuracyHorizontal `json:"accuracy_h,omitempty"`

	// AccuracyV Vertical error that is likely to be present in this reported position. This is the GVA enumeration from ADS-B, plus some finer values for UAS.
	AccuracyV *PositionAccuracyVertical `json:"accuracy_v,omitempty"`
	Altitude  *Altitude                 `json:"altitude,omitempty"`

	// Extrapolated True if this position was generated primarily by computation rather than primarily from a direct instrument measurement.
	Extrapolated *bool `json:"extrapolated,omitempty"`

	// Latitude Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.
	//
	// Example: 34.123
	Latitude *Latitude `json:"latitude,omitempty"`

	// Longitude Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.
	//
	// Example: -118.456
	Longitude *Longitude `json:"longitude,omitempty"`
}

// PositionAccuracyHorizontal Horizontal error that is likely to be present in this reported position. This is the NACp enumeration from ADS-B, plus 1m for a more complete range for UAS.
type PositionAccuracyHorizontal string

// PositionAccuracyVertical Vertical error that is likely to be present in this reported position. This is the GVA enumeration from ADS-B, plus some finer values for UAS.
type PositionAccuracyVertical string

// PositionRecord A record of vehicle telemetry information received by this USS (typically for conformance monitoring).
type PositionRecord struct {
	// Telemetry Vehicle position, altitude, and velocity.
	Telemetry VehicleTelemetry `json:"telemetry"`

	// TimeReceived Time that this position data was received by the USS
	TimeReceived PositionRecord_TimeReceived `json:"time_received"`
}

// PositionRecord_TimeReceived Time that this position data was received by the USS
type PositionRecord_TimeReceived = Time

// Priority Ordinal priority of the operational intent, as defined by the regulator.  Operational intents with lesser values are lower priority than all operational intents with greater values.  A lower-priority operational intent may not create a conflict with a higher-priority operational intent.  A higher-priority operational intent may create a conflict with a lower-priority operational intent.  The regulator specifies whether an operational intent may create a conflict with other operational intents of the same priority.
type Priority = int

// PutConstraintDetailsParameters Parameters of a message informing of new full information for a constraint.  Pushed (by a client, not the DSS) directly to clients with subscriptions when another client makes a change to airspace within a cell with a subscription.
type PutConstraintDetailsParameters struct {
	// Constraint Full information about the constraint that has changed.  If this field is omitted, the constraint was deleted.  The `ovn` field in the nested `reference` must be populated.
	Constraint *PutConstraintDetailsParameters_Constraint `json:"constraint,omitempty"`

	// ConstraintId ID of constraint that has changed.
	ConstraintId PutConstraintDetailsParameters_ConstraintId `json:"constraint_id"`

	// Subscriptions Subscription(s) prompting this notification.
	Subscriptions []SubscriptionState `json:"subscriptions"`
}

// PutConstraintDetailsParameters_Constraint Full information about the constraint that has changed.  If this field is omitted, the constraint was deleted.  The `ovn` field in the nested `reference` must be populated.
type PutConstraintDetailsParameters_Constraint = Constraint

// PutConstraintDetailsParameters_ConstraintId ID of constraint that has changed.
type PutConstraintDetailsParameters_ConstraintId = EntityID

// PutConstraintReferenceParameters Parameters for a request to create/update a ConstraintReference in the DSS.
type PutConstraintReferenceParameters struct {
	// Extents Spacetime extents that bound this constraint.
	// The end time may not be in the past.
	// All volumes of the constraint must be encompassed in these extents. However, these extents do not need to match the precise volumes of the constraint; a single bounding extent may be provided instead, for instance.
	Extents []Volume4D `json:"extents"`

	// UssBaseUrl The base URL of a USS implementation that implements the parts of the USS-USS API necessary for providing the details of this constraint.
	UssBaseUrl ConstraintUssBaseURL `json:"uss_base_url"`
}

// PutOperationalIntentDetailsParameters Parameters of a message informing of detailed information for a peer operational intent. Pushed (by a client, not the DSS) directly to clients with subscriptions when another client makes a change to airspace within a cell with a subscription.
type PutOperationalIntentDetailsParameters struct {
	// OperationalIntent Full information about the operational intent that has changed.  If this field is omitted, the operational intent was deleted.  The `ovn` field in the nested `reference` must be populated.
	OperationalIntent *PutOperationalIntentDetailsParameters_OperationalIntent `json:"operational_intent,omitempty"`

	// OperationalIntentId ID of operational intent that has changed.
	OperationalIntentId PutOperationalIntentDetailsParameters_OperationalIntentId `json:"operational_intent_id"`

	// Subscriptions Subscription(s) prompting this notification.
	Subscriptions []SubscriptionState `json:"subscriptions"`
}

// PutOperationalIntentDetailsParameters_OperationalIntent Full information about the operational intent that has changed.  If this field is omitted, the operational intent was deleted.  The `ovn` field in the nested `reference` must be populated.
type PutOperationalIntentDetailsParameters_OperationalIntent = OperationalIntent

// PutOperationalIntentDetailsParameters_OperationalIntentId ID of operational intent that has changed.
type PutOperationalIntentDetailsParameters_OperationalIntentId = EntityID

// PutOperationalIntentReferenceParameters Parameters for a request to create an OperationalIntentReference in the DSS. A subscription to changes overlapping this volume may be implicitly created, but this can be overridden by providing the (optional) 'subscription_id' to use. Note: The implicit subscription is managed by the DSS, not the USS.
type PutOperationalIntentReferenceParameters struct {
	// Extents Spacetime extents that bound this operational intent.
	// Start and end times, as well as lower and upper altitudes, are required for each volume. The end time may not be in the past. All volumes, both nominal and off-nominal, must be encompassed in these extents. However, these extents do not need to match the precise volumes of the operational intent; a single bounding extent may be provided instead, for instance.
	Extents []Volume4D `json:"extents"`

	// Key Proof that the USS creating or mutating this operational intent was aware of the current state of the airspace, with the expectation that this operational intent is therefore deconflicted from all relevant features in the airspace.  This field is not required when declaring an operational intent Nonconforming or Contingent, or when there are no relevant Entities in the airspace, but is otherwise required. OVNs for constraints are required if and only if the USS managing this operational intent is performing the constraint processing role, which is indicated by whether the subscription associated with this operational intent triggers notifications for constraints.  The key does not need to contain the OVN for the operational intent being updated.
	Key *PutOperationalIntentReferenceParameters_Key `json:"key,omitempty"`

	// NewSubscription If an existing subscription is not specified in `subscription_id`, and the operational intent is in the Activated, Nonconforming, or Contingent state, then this field must be populated.  When this field is populated, an implicit subscription will be created and associated with this operational intent, and will generally be deleted automatically upon the deletion of this operational intent.
	NewSubscription *PutOperationalIntentReferenceParameters_NewSubscription `json:"new_subscription,omitempty"`

	// RequestedOvnSuffix This optional field not part of the original F3548 standard API allows a USS to request a specific OVN when creating or updating an operational intent. When creating an operational intent, this enables a USS to immediately publish the operational intent details with the expected OVN. When updating an operational intent, this enables a USS to immediately make available this new version of the operational intent details if specifically requested by the remote USS. The USS must still wait for the DSS receipt to actually publish the new operational intent details. This allows USSs to obtain correct operational intent details even if the DSS takes a long time to respond and/or the USS processing  it.
	// The requested suffix must be a UUIDv7 string containing a timestamp of the current time. If the suffix is invalid, and notably if the time is too far in the past or the future, the request will be rejected. If the suffix is valid, the DSS will set the OVN of the operational intent to be `{entityid}_{requested_ovn_suffix}`. If no suffix is set, the DSS will proceed as specified by the standard.
	RequestedOvnSuffix *PutOperationalIntentReferenceParameters_RequestedOvnSuffix `json:"requested_ovn_suffix,omitempty"`

	// State State of an operational intent.
	// 'Accepted': Operational intent is created and shared, but not yet in use; see standard text for more details.
	// The create or update request for this operational intent reference must include a Key containing all OVNs for all relevant Entities.
	// 'Activated': Operational intent is in active use; see standard text for more details.
	// The create or update request for this operational intent reference must include a Key containing all OVNs for all relevant Entities.
	// 'Nonconforming': UA is temporarily outside its volumes, but the situation is expected to be recoverable; see standard text for more details.
	// In this state, the `/uss/v1/operational_intents/{entityid}/telemetry` USS-USS endpoint should respond, if available, to queries from USS peers.  The create or update request for this operational intent may omit a Key in this case because the operational intent is being adjusted as flown and cannot necessarily deconflict.
	// 'Contingent': UA is considered unrecoverably unable to conform with its coordinate operational intent; see standard text for more details.
	// This state must transition to Ended.  In this state, the `/uss/v1/operational_intents/{entityid}/telemetry` USS-USS endpoint should respond, if available, to queries from USS peers.  The create or update request for this operational intent may omit a Key in this case because the operational intent is being adjusted as flown and cannot necessarily deconflict.
	State OperationalIntentState `json:"state"`

	// SubscriptionId The ID of an existing subscription that the USS will use to keep the operator informed about updates to relevant airspace information. If this field is not provided when the operational intent is in the Activated, Nonconforming, or Contingent state, then the `new_subscription` field must be provided in order to provide notification capability for the operational intent.  The subscription specified by this ID must cover at least the area over which this operational intent is conducted, and it must provide notifications for operational intents.
	SubscriptionId *PutOperationalIntentReferenceParameters_SubscriptionId `json:"subscription_id,omitempty"`

	// UssBaseUrl The base URL of a USS implementation that implements the parts of the USS-USS API necessary for providing the details of this operational intent, and telemetry during non-conformance or contingency, if applicable.
	UssBaseUrl OperationalIntentUssBaseURL `json:"uss_base_url"`
}

// PutOperationalIntentReferenceParameters_Key Proof that the USS creating or mutating this operational intent was aware of the current state of the airspace, with the expectation that this operational intent is therefore deconflicted from all relevant features in the airspace.  This field is not required when declaring an operational intent Nonconforming or Contingent, or when there are no relevant Entities in the airspace, but is otherwise required. OVNs for constraints are required if and only if the USS managing this operational intent is performing the constraint processing role, which is indicated by whether the subscription associated with this operational intent triggers notifications for constraints.  The key does not need to contain the OVN for the operational intent being updated.
type PutOperationalIntentReferenceParameters_Key = Key

// PutOperationalIntentReferenceParameters_NewSubscription If an existing subscription is not specified in `subscription_id`, and the operational intent is in the Activated, Nonconforming, or Contingent state, then this field must be populated.  When this field is populated, an implicit subscription will be created and associated with this operational intent, and will generally be deleted automatically upon the deletion of this operational intent.
type PutOperationalIntentReferenceParameters_NewSubscription = ImplicitSubscriptionParameters

// PutOperationalIntentReferenceParameters_RequestedOvnSuffix This optional field not part of the original F3548 standard API allows a USS to request a specific OVN when creating or updating an operational intent. When creating an operational intent, this enables a USS to immediately publish the operational intent details with the expected OVN. When updating an operational intent, this enables a USS to immediately make available this new version of the operational intent details if specifically requested by the remote USS. The USS must still wait for the DSS receipt to actually publish the new operational intent details. This allows USSs to obtain correct operational intent details even if the DSS takes a long time to respond and/or the USS processing  it.
// The requested suffix must be a UUIDv7 string containing a timestamp of the current time. If the suffix is invalid, and notably if the time is too far in the past or the future, the request will be rejected. If the suffix is valid, the DSS will set the OVN of the operational intent to be `{entityid}_{requested_ovn_suffix}`. If no suffix is set, the DSS will proceed as specified by the standard.
type PutOperationalIntentReferenceParameters_RequestedOvnSuffix = UUIDv7Format

// PutOperationalIntentReferenceParameters_SubscriptionId The ID of an existing subscription that the USS will use to keep the operator informed about updates to relevant airspace information. If this field is not provided when the operational intent is in the Activated, Nonconforming, or Contingent state, then the `new_subscription` field must be provided in order to provide notification capability for the operational intent.  The subscription specified by this ID must cover at least the area over which this operational intent is conducted, and it must provide notifications for operational intents.
type PutOperationalIntentReferenceParameters_SubscriptionId = EntityID

// PutSubscriptionParameters Parameters for a request to create/update a subscription in the DSS.  At least one form of notifications must be requested.
type PutSubscriptionParameters struct {
	// Extents Spacetime extents of the volume to subscribe to.
	// This subscription will automatically be deleted after its end time if it has not been refreshed by then. If end time is not specified, the value will be chosen automatically by the DSS. If start time is not specified, it will default to the time the request is processed. The end time may not be in the past.
	// Note that some Entities triggering notifications may lie entirely outside the requested area.
	Extents PutSubscriptionParameters_Extents `json:"extents"`

	// NotifyForConstraints If true, trigger notifications when constraints are created, updated, or deleted.  Otherwise, changes in constraints should not trigger notifications.  The scope utm.constraint_processing is required to set this flag true.
	NotifyForConstraints *bool `json:"notify_for_constraints,omitempty"`

	// NotifyForOperationalIntents If true, trigger notifications when operational intents are created, updated, or deleted.  Otherwise, changes in operational intents should not trigger notifications.  The scope utm.strategic_coordination is required to set this flag true.
	NotifyForOperationalIntents *bool `json:"notify_for_operational_intents,omitempty"`

	// UssBaseUrl The base URL of a USS implementation of the parts of the USS-USS API necessary for receiving the notifications requested by this subscription.
	UssBaseUrl SubscriptionUssBaseURL `json:"uss_base_url"`
}

// PutSubscriptionParameters_Extents Spacetime extents of the volume to subscribe to.
// This subscription will automatically be deleted after its end time if it has not been refreshed by then. If end time is not specified, the value will be chosen automatically by the DSS. If start time is not specified, it will default to the time the request is processed. The end time may not be in the past.
// Note that some Entities triggering notifications may lie entirely outside the requested area.
type PutSubscriptionParameters_Extents = Volume4D

// PutSubscriptionResponse Response for a request to create or update a subscription.
type PutSubscriptionResponse struct {
	// ConstraintReferences Constraints in or near the subscription area at the time of creation/update, if `notify_for_constraints` is true.
	ConstraintReferences *[]ConstraintReference `json:"constraint_references,omitempty"`

	// OperationalIntentReferences Operational intents in or near the subscription area at the time of creation/update, if `notify_for_operational_intents` is true.
	OperationalIntentReferences *[]OperationalIntentReference `json:"operational_intent_references,omitempty"`

	// Subscription Specification of a geographic area that a client is interested in on an ongoing basis (e.g., "planning area").
	Subscription Subscription `json:"subscription"`
}

// QueryConstraintReferenceParameters Parameters for a request to find ConstraintReferences matching the provided criteria.
type QueryConstraintReferenceParameters struct {
	// AreaOfInterest Contiguous block of geographic spacetime.
	AreaOfInterest *Volume4D `json:"area_of_interest,omitempty"`
}

// QueryConstraintReferencesResponse Response to DSS query for ConstraintReferences in an area of interest.
type QueryConstraintReferencesResponse struct {
	// ConstraintReferences ConstraintReferences in the area of interest.
	ConstraintReferences []ConstraintReference `json:"constraint_references"`
}

// QueryOperationalIntentReferenceParameters Parameters for a request to find OperationalIntentReferences matching the provided criteria.
type QueryOperationalIntentReferenceParameters struct {
	// AreaOfInterest Contiguous block of geographic spacetime.
	AreaOfInterest *Volume4D `json:"area_of_interest,omitempty"`
}

// QueryOperationalIntentReferenceResponse Response to DSS query for OperationalIntentReferences in an area of interest.
type QueryOperationalIntentReferenceResponse struct {
	// OperationalIntentReferences OperationalIntentReferences in the area of interest.
	OperationalIntentReferences []OperationalIntentReference `json:"operational_intent_references"`
}

// QuerySubscriptionParameters Parameters for a request to find subscriptions matching the provided criteria.
type QuerySubscriptionParameters struct {
	// AreaOfInterest Contiguous block of geographic spacetime.
	AreaOfInterest *Volume4D `json:"area_of_interest,omitempty"`
}

// QuerySubscriptionsResponse Response to DSS query for subscriptions in a particular geographic area.
type QuerySubscriptionsResponse struct {
	// Subscriptions Subscriptions that overlap the specified geographic area.
	Subscriptions []Subscription `json:"subscriptions"`
}

// Radius defines model for Radius.
type Radius struct {
	// Units FIXM-compatible units.  Only meters ("M") are acceptable for UTM.
	Units RadiusUnits `json:"units"`

	// Value Distance from the centerpoint of a circular area, along the WGS84 ellipsoid.
	//
	// Example: 300.183
	Value float32 `json:"value"`
}

// RadiusUnits FIXM-compatible units.  Only meters ("M") are acceptable for UTM.
type RadiusUnits string

// SetUssAvailabilityStatusParameters defines model for SetUssAvailabilityStatusParameters.
type SetUssAvailabilityStatusParameters struct {
	// Availability A USS is presumed to be in the Unknown state absent indication otherwise by a USS with availability arbitration scope.  Upon determination via availability arbitration, a USS is Down when it does not respond appropriately, and a Down USS may not perform the following operations in the DSS:
	// * Create an operational intent in the Accepted or Activated states
	// * Modify an operational intent whose new or unchanged state is Accepted or Activated
	// * Delete an operational intent
	// A USS in the Unknown state possesses all the capabilities, within the DSS, of a USS in the Normal state.
	Availability UssAvailabilityState `json:"availability"`

	// OldVersion Version of USS's availability to change, for consistent read-modify-write operations and consistent retry behavior.
	OldVersion string `json:"old_version"`
}

// SubscriberToNotify Subscriber to notify of a change in the airspace.  This is provided by the DSS to a client changing the airspace, and it is the responsibility of that client to send a notification to the specified USS according to the change made to the airspace.
type SubscriberToNotify struct {
	// Subscriptions Subscription(s) prompting this notification.
	Subscriptions []SubscriptionState `json:"subscriptions"`

	// UssBaseUrl The base URL of a USS implementation of the parts of the USS-USS API necessary for receiving the notifications requested by this subscription.
	UssBaseUrl SubscriptionUssBaseURL `json:"uss_base_url"`
}

// Subscription Specification of a geographic area that a client is interested in on an ongoing basis (e.g., "planning area").
type Subscription struct {
	// DependentOperationalIntents List of IDs for operational intents that are dependent on this subscription.
	DependentOperationalIntents *[]EntityID `json:"dependent_operational_intents,omitempty"`

	// Id Identifier for a subscription communicated through the DSS.  Formatted as a UUIDv4.
	//
	// Example: 78ea3fe8-71c2-4f5c-9b44-9c02f5563c6f
	Id SubscriptionID `json:"id"`

	// ImplicitSubscription True if this subscription was implicitly created by the DSS via the creation of an operational intent, and should therefore be deleted by the DSS when that operational intent is deleted.
	ImplicitSubscription *bool `json:"implicit_subscription,omitempty"`

	// NotificationIndex Tracks the notifications sent for a subscription so the subscriber can detect missed notifications more easily.
	NotificationIndex SubscriptionNotificationIndex `json:"notification_index"`

	// NotifyForConstraints If true, trigger notifications when constraints are created, updated, or deleted.  Otherwise, changes in constraints should not trigger notifications.  The scope utm.constraint_processing is required to set this flag true.
	NotifyForConstraints *bool `json:"notify_for_constraints,omitempty"`

	// NotifyForOperationalIntents If true, trigger notifications when operational intents are created, updated, or deleted.  Otherwise, changes in operational intents should not trigger notifications.  The scope utm.strategic_coordination is required to set this flag true.
	NotifyForOperationalIntents *bool `json:"notify_for_operational_intents,omitempty"`

	// TimeEnd If set, this subscription will not receive notifications involving airspace changes entirely after this time.
	TimeEnd *Subscription_TimeEnd `json:"time_end,omitempty"`

	// TimeStart If set, this subscription will not receive notifications involving airspace changes entirely before this time.
	TimeStart *Subscription_TimeStart `json:"time_start,omitempty"`

	// UssBaseUrl The base URL of a USS implementation of the parts of the USS-USS API necessary for receiving the notifications requested by this subscription.
	UssBaseUrl SubscriptionUssBaseURL `json:"uss_base_url"`

	// Version Version of the subscription that the DSS changes every time a USS changes the subscription.  The DSS incrementing the notification_index does not constitute a change that triggers a new version.  A USS must specify this version when modifying an existing subscription to ensure consistency in read-modify-write operations and distributed systems.
	Version string `json:"version"`
}

// Subscription_TimeEnd If set, this subscription will not receive notifications involving airspace changes entirely after this time.
type Subscription_TimeEnd = Time

// Subscription_TimeStart If set, this subscription will not receive notifications involving airspace changes entirely before this time.
type Subscription_TimeStart = Time

// SubscriptionID Identifier for a subscription communicated through the DSS.  Formatted as a UUIDv4.
//
// Example: 78ea3fe8-71c2-4f5c-9b44-9c02f5563c6f
type SubscriptionID = UUIDv4Format

// SubscriptionNotificationIndex Tracks the notifications sent for a subscription so the subscriber can detect missed notifications more easily.
type SubscriptionNotificationIndex = int32

// SubscriptionState State of subscription which is causing a notification to be sent.
type SubscriptionState struct {
	// NotificationIndex Tracks the notifications sent for a subscription so the subscriber can detect missed notifications more easily.
	NotificationIndex SubscriptionNotificationIndex `json:"notification_index"`

	// SubscriptionId Identifier for a subscription communicated through the DSS.  Formatted as a UUIDv4.
	//
	// Example: 78ea3fe8-71c2-4f5c-9b44-9c02f5563c6f
	SubscriptionId SubscriptionID `json:"subscription_id"`
}

// SubscriptionUssBaseURL The base URL of a USS implementation of the parts of the USS-USS API necessary for receiving the notifications requested by this subscription.
type SubscriptionUssBaseURL = UssBaseURL

// TextShortType A free text with a maximum length of 200 characters
type TextShortType = string

// Time defines model for Time.
type Time struct {
	Format TimeFormat `json:"format"`

	// Value RFC3339-formatted time/date string.  The time zone must be 'Z'.
	//
	// Example: 1985-04-12T23:20:50.52Z
	Value time.Time `json:"value"`
}

// TimeFormat defines model for Time.Format.
type TimeFormat string

// USSLogSet The set of log data fulfilling this standard's Logging requirements.
type USSLogSet struct {
	// ConstraintProviderAssociations For a USS that performs constraint management, associations of an authorized constraint provider with all constraints that transition to the valid state.
	ConstraintProviderAssociations *[]ConstraintProviderAssociation `json:"constraint_provider_associations,omitempty"`

	// Messages Outgoing messages sent to other USSs and the DSS, and incoming messages received from other USSs, including instances where an expected response to a request is not received.
	Messages *[]ExchangeRecord `json:"messages,omitempty"`

	// OperationalIntentPositions For a USS performing conformance monitoring, all position data used for conformance monitoring that is ingested from the UA.
	OperationalIntentPositions *[]OperationalIntentPositions `json:"operational_intent_positions,omitempty"`

	// OperatorAssociations For a USS that manages operational intents, associations of an operator with operational intents that transitioned to the Accepted state.
	OperatorAssociations *[]OperatorAssociation `json:"operator_associations,omitempty"`

	// OperatorInputs Instances of operator input as specifically required within this standard.
	OperatorInputs *[]UserInputRecord `json:"operator_inputs,omitempty"`

	// OperatorNotifications Instances of operator notifications as specifically required within this standard.
	OperatorNotifications *[]UserNotificationRecord `json:"operator_notifications,omitempty"`

	// PlanningAttempts For a USS that manages operational intents, instances where an operational intent could not be planned or replanned due to conflicts with other operational intents or constraints.
	PlanningAttempts *[]PlanningRecord `json:"planning_attempts,omitempty"`
}

// UUIDv4Format String whose format matches a version-4 UUID according to RFC 4122.
//
// Example: 03e5572a-f733-49af-bc14-8a18bd53ee39
type UUIDv4Format = string

// UUIDv7Format String whose format matches a version-7 UUID according to RFC 9562.
//
// Example: 0191b794-9628-745a-a598-aa1fcd4a82bf
type UUIDv7Format = string

// UserInputRecord User input record
type UserInputRecord struct {
	// InputDetails Description of the information that was provided by the user, as per the referenced input_triggering_event requirement
	InputDetails *string `json:"input_details,omitempty"`

	// InputTriggeringEvent Requirement ID that pertains to the given notification
	InputTriggeringEvent UserInputRecordInputTriggeringEvent `json:"input_triggering_event"`

	// OperationalIntentId ID of the operational_intent ID pertaining to the user input
	OperationalIntentId UserInputRecord_OperationalIntentId `json:"operational_intent_id"`

	// TriggeringEventTime Time in which user input was received by the USS
	TriggeringEventTime UserInputRecord_TriggeringEventTime `json:"triggering_event_time"`
}

// UserInputRecordInputTriggeringEvent Requirement ID that pertains to the given notification
type UserInputRecordInputTriggeringEvent string

// UserInputRecord_OperationalIntentId ID of the operational_intent ID pertaining to the user input
type UserInputRecord_OperationalIntentId = EntityID

// UserInputRecord_TriggeringEventTime Time in which user input was received by the USS
type UserInputRecord_TriggeringEventTime = Time

// UserNotificationRecord User notification record.
type UserNotificationRecord struct {
	// NotificationDetails Description of information that was provided to the user, as per the referenced notification_triggering_event requirement
	NotificationDetails *string `json:"notification_details,omitempty"`

	// NotificationTime Time at which the user was notified
	NotificationTime UserNotificationRecord_NotificationTime `json:"notification_time"`

	// NotificationTriggeringEvent Requirement ID that pertains to the given notification
	NotificationTriggeringEvent UserNotificationRecordNotificationTriggeringEvent `json:"notification_triggering_event"`

	// TriggeringEventTime Time of the notification triggering event
	TriggeringEventTime UserNotificationRecord_TriggeringEventTime `json:"triggering_event_time"`
}

// UserNotificationRecord_NotificationTime Time at which the user was notified
type UserNotificationRecord_NotificationTime = Time

// UserNotificationRecordNotificationTriggeringEvent Requirement ID that pertains to the given notification
type UserNotificationRecordNotificationTriggeringEvent string

// UserNotificationRecord_TriggeringEventTime Time of the notification triggering event
type UserNotificationRecord_TriggeringEventTime = Time

// UssAvailabilityState A USS is presumed to be in the Unknown state absent indication otherwise by a USS with availability arbitration scope.  Upon determination via availability arbitration, a USS is Down when it does not respond appropriately, and a Down USS may not perform the following operations in the DSS:
// * Create an operational intent in the Accepted or Activated states
// * Modify an operational intent whose new or unchanged state is Accepted or Activated
// * Delete an operational intent
// A USS in the Unknown state possesses all the capabilities, within the DSS, of a USS in the Normal state.
type UssAvailabilityState string

// UssAvailabilityStatus defines model for UssAvailabilityStatus.
type UssAvailabilityStatus struct {
	// Availability A USS is presumed to be in the Unknown state absent indication otherwise by a USS with availability arbitration scope.  Upon determination via availability arbitration, a USS is Down when it does not respond appropriately, and a Down USS may not perform the following operations in the DSS:
	// * Create an operational intent in the Accepted or Activated states
	// * Modify an operational intent whose new or unchanged state is Accepted or Activated
	// * Delete an operational intent
	// A USS in the Unknown state possesses all the capabilities, within the DSS, of a USS in the Normal state.
	Availability UssAvailabilityState `json:"availability"`

	// Uss Client ID (matching their `sub` in access tokens) of the USS to which this availability applies.
	Uss string `json:"uss"`
}

// UssAvailabilityStatusResponse defines model for UssAvailabilityStatusResponse.
type UssAvailabilityStatusResponse struct {
	Status UssAvailabilityStatus `json:"status"`

	// Version Current version of USS's availability.  Used to change USS's availability.
	Version string `json:"version"`
}

// UssBaseURL The base URL of a USS implementation of part or all of the USS-USS API. Per the USS-USS API, the full URL of a particular resource can be constructed by appending, e.g., `/uss/v1/{resource}/{id}` to this base URL. Accordingly, this URL may not have a trailing '/' character.
//
// Example: https://uss.example.com/utm
type UssBaseURL = string

// VehicleTelemetry Vehicle position, altitude, and velocity.
type VehicleTelemetry struct {
	// Position Location of the vehicle (UAS) as reported for UTM. Note: 'accuracy' values are required when extrapolated field is true.
	Position     *Position `json:"position,omitempty"`
	TimeMeasured Time      `json:"time_measured"`
	Velocity     *Velocity `json:"velocity,omitempty"`
}

// Velocity defines model for Velocity.
type Velocity struct {
	// Speed Ground speed in meters/second.
	//
	// Example: 200.1
	Speed float32 `json:"speed"`

	// Track Direction of flight expressed as a "True North-based" ground track angle. This value is provided in degrees East of North with a minimum resolution of 1 degree. A value of 360 indicates invalid, no value, or unknown.
	//
	// Example: 120
	Track      *float32           `json:"track,omitempty"`
	UnitsSpeed VelocityUnitsSpeed `json:"units_speed"`
}

// VelocityUnitsSpeed defines model for Velocity.UnitsSpeed.
type VelocityUnitsSpeed string

// Volume3D A three-dimensional geographic volume consisting of a vertically-extruded shape. Exactly one outline must be specified.
type Volume3D struct {
	// AltitudeLower Minimum bounding altitude of this volume. Must be less than altitude_upper, if specified.
	AltitudeLower *Volume3D_AltitudeLower `json:"altitude_lower,omitempty"`

	// AltitudeUpper Maximum bounding altitude of this volume. Must be greater than altitude_lower, if specified.
	AltitudeUpper *Volume3D_AltitudeUpper `json:"altitude_upper,omitempty"`

	// OutlineCircle A circular geographic shape on the surface of the earth.
	OutlineCircle *Volume3D_OutlineCircle `json:"outline_circle,omitempty"`

	// OutlinePolygon A polygonal geographic shape on the surface of the earth.
	OutlinePolygon *Volume3D_OutlinePolygon `json:"outline_polygon,omitempty"`
}

// Volume3D_AltitudeLower Minimum bounding altitude of this volume. Must be less than altitude_upper, if specified.
type Volume3D_AltitudeLower = Altitude

// Volume3D_AltitudeUpper Maximum bounding altitude of this volume. Must be greater than altitude_lower, if specified.
type Volume3D_AltitudeUpper = Altitude

// Volume3D_OutlineCircle A circular geographic shape on the surface of the earth.
type Volume3D_OutlineCircle = Circle

// Volume3D_OutlinePolygon A polygonal geographic shape on the surface of the earth.
type Volume3D_OutlinePolygon = Polygon

// Volume4D Contiguous block of geographic spacetime.
type Volume4D struct {
	// TimeEnd End time of this volume. Must be after time_start.
	TimeEnd *Volume4D_TimeEnd `json:"time_end,omitempty"`

	// TimeStart Beginning time of this volume. Must be before time_end.
	TimeStart *Volume4D_TimeStart `json:"time_start,omitempty"`

	// Volume A three-dimensional geographic volume consisting of a vertically-extruded shape. Exactly one outline must be specified.
	Volume Volume3D `json:"volume"`
}

// Volume4D_TimeEnd End time of this volume. Must be after time_start.
type Volume4D_TimeEnd = Time

// Volume4D_TimeStart Beginning time of this volume. Must be before time_end.
type Volume4D_TimeStart = Time

// GetOperationalIntentDetailsParams defines parameters for GetOperationalIntentDetails.
type GetOperationalIntentDetailsParams struct {
	// Version This optional field not part of the original F3548 standard API allows a remote USS to request a specific version of the operational intent details.  USSs are not required to implement support for this field.  If implemented, the USS must make available the published and the pending versions of the operational intent.  It is not required for older versions to be available.
	Version *EntityVersion `form:"version,omitempty" json:"version,omitempty"`
}

// QueryConstraintReferencesJSONRequestBody defines body for QueryConstraintReferences for application/json ContentType.
type QueryConstraintReferencesJSONRequestBody = QueryConstraintReferenceParameters

// CreateConstraintReferenceJSONRequestBody defines body for CreateConstraintReference for application/json ContentType.
type CreateConstraintReferenceJSONRequestBody = PutConstraintReferenceParameters

// UpdateConstraintReferenceJSONRequestBody defines body for UpdateConstraintReference for application/json ContentType.
type UpdateConstraintReferenceJSONRequestBody = PutConstraintReferenceParameters

// QueryOperationalIntentReferencesJSONRequestBody defines body for QueryOperationalIntentReferences for application/json ContentType.
type QueryOperationalIntentReferencesJSONRequestBody = QueryOperationalIntentReferenceParameters

// CreateOperationalIntentReferenceJSONRequestBody defines body for CreateOperationalIntentReference for application/json ContentType.
type CreateOperationalIntentReferenceJSONRequestBody = PutOperationalIntentReferenceParameters

// UpdateOperationalIntentReferenceJSONRequestBody defines body for UpdateOperationalIntentReference for application/json ContentType.
type UpdateOperationalIntentReferenceJSONRequestBody = PutOperationalIntentReferenceParameters

// MakeDssReportJSONRequestBody defines body for MakeDssReport for application/json ContentType.
type MakeDssReportJSONRequestBody = ErrorReport

// QuerySubscriptionsJSONRequestBody defines body for QuerySubscriptions for application/json ContentType.
type QuerySubscriptionsJSONRequestBody = QuerySubscriptionParameters

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = PutSubscriptionParameters

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = PutSubscriptionParameters

// SetUssAvailabilityJSONRequestBody defines body for SetUssAvailability for application/json ContentType.
type SetUssAvailabilityJSONRequestBody = SetUssAvailabilityStatusParameters

// NotifyConstraintDetailsChangedJSONRequestBody defines body for NotifyConstraintDetailsChanged for application/json ContentType.
type NotifyConstraintDetailsChangedJSONRequestBody = PutConstraintDetailsParameters

// NotifyOperationalIntentDetailsChangedJSONRequestBody defines body for NotifyOperationalIntentDetailsChanged for application/json ContentType.
type NotifyOperationalIntentDetailsChangedJSONRequestBody = PutOperationalIntentDetailsParameters

// MakeUssReportJSONRequestBody defines body for MakeUssReport for application/json ContentType.
type MakeUssReportJSONRequestBody = ErrorReport
